<?php

return [
    'page' => [
        'title' => 'Anmol Pushjai Goel',
        'seo_title' => 'Anmol Pushjai Goel — Entrepreneur · Tech & AI Policy Voice · Author',
        'meta_description' => 'Anmol Pushjai Goel — Founder & CEO of Nuclear Edge, Trustee of the Bharat Governance Council, and a leading Indian voice on AI policy, technology and society.',
        'og_image' => 'images/home/anmol-pushjai-goel-portrait.jpg',
    ],

    'sections' => [
        'hero' => [
            'name' => 'Hero',
            'type' => 'hero',
            'sort_order' => 10,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 180],
                'title_first' => ['label' => 'Title line one', 'type' => 'text', 'max' => 100],
                'title_second' => ['label' => 'Title line two', 'type' => 'text', 'max' => 100],
                'roles' => [
                    'label' => 'Roles',
                    'type' => 'repeater',
                    'max_items' => 8,
                    'fields' => [
                        'label' => ['label' => 'Role', 'type' => 'text', 'max' => 160],
                    ],
                ],
                'description' => ['label' => 'Introduction', 'type' => 'textarea', 'max' => 1200],
                'scroll_label' => ['label' => 'Scroll label', 'type' => 'text', 'max' => 40],
                'image' => ['label' => 'Portrait', 'type' => 'image'],
                'image_alt' => ['label' => 'Portrait alt text', 'type' => 'text', 'max' => 180],
            ],
            'content' => [
                'eyebrow' => 'Entrepreneur · Tech & AI Policy Voice · Author',
                'title_first' => 'Anmol Pushjai',
                'title_second' => 'Goel',
                'roles' => [
                    ['_key' => 'hero-role-1', 'label' => 'Founder & CEO, Nuclear Edge'],
                    ['_key' => 'hero-role-2', 'label' => 'Trustee, Bharat Governance Council'],
                    ['_key' => 'hero-role-3', 'label' => 'Govt. of India Advisor'],
                ],
                'description' => 'An entrepreneur and policy voice working at the intersection of deep technology and Indian society — building Nuclear Edge, shaping AI and governance policy, and writing with a directness the field rarely allows itself.',
                'scroll_label' => 'Scroll',
                'image' => 'images/home/anmol-pushjai-goel-portrait.jpg',
                'image_alt' => 'Portrait of Anmol Pushjai Goel',
            ],
        ],
        'creed' => [
            'name' => 'Positioning Strip',
            'type' => 'creed',
            'sort_order' => 20,
            'fields' => [
                'statement' => ['label' => 'Statement', 'type' => 'textarea', 'max' => 600],
                'accent' => ['label' => 'Gold accent text', 'type' => 'text', 'max' => 180],
                'highlights' => [
                    'label' => 'Highlights',
                    'type' => 'repeater',
                    'max_items' => 8,
                    'fields' => [
                        'title' => ['label' => 'Title', 'type' => 'text', 'max' => 100],
                        'description' => ['label' => 'Description', 'type' => 'text', 'max' => 220],
                    ],
                ],
            ],
            'content' => [
                'statement' => 'A single thread runs through the company, the policy work and the writing —',
                'accent' => 'conviction, put to work.',
                'highlights' => [
                    ['_key' => 'creed-1', 'title' => 'Nuclear Edge', 'description' => 'Founder & CEO · Deep-tech consulting'],
                    ['_key' => 'creed-2', 'title' => 'Bharat', 'description' => 'Trustee, Bharat Governance Council'],
                    ['_key' => 'creed-3', 'title' => 'Union Govt.', 'description' => 'Advisory & board roles, ministries'],
                    ['_key' => 'creed-4', 'title' => 'Psych · Phil · Soc', 'description' => 'An interdisciplinary lens on technology'],
                ],
            ],
        ],
        'industries_intro' => [
            'name' => 'Industries Introduction',
            'type' => 'industries_intro',
            'sort_order' => 30,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading_first' => ['label' => 'Heading line one', 'type' => 'text', 'max' => 140],
                'heading_second' => ['label' => 'Heading line two', 'type' => 'text', 'max' => 140],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1800],
                'image' => ['label' => 'Section image', 'type' => 'image'],
                'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                'image_tag' => ['label' => 'Image tag', 'type' => 'text', 'max' => 80],
                'facts' => [
                    'label' => 'Company facts',
                    'type' => 'repeater',
                    'max_items' => 12,
                    'fields' => [
                        'label' => ['label' => 'Focus', 'type' => 'text', 'max' => 180],
                        'value' => ['label' => 'Role/value', 'type' => 'text', 'max' => 140],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'The Company',
                'heading_first' => 'Nuclear Edge.',
                'heading_second' => "Deep tech, on India's terms.",
                'description' => "A deep-technology and business-consulting firm headquartered in Bengaluru with a presence in Alberta, Canada — built on the conviction that industry shouldn't wait for regulation to catch up with innovation, but should actively shape the policy environment with ambition and accountability.",
                'image' => 'images/home/nuclear-edge-industries.jpg',
                'image_alt' => 'Anmol Pushjai Goel — industries',
                'image_tag' => 'Nuclear Edge',
                'facts' => [
                    ['_key' => 'industry-fact-1', 'label' => 'Deep-Tech & Digital Transformation', 'value' => 'Founder & CEO'],
                    ['_key' => 'industry-fact-2', 'label' => 'Blockchain & Enterprise Strategy', 'value' => 'Architect'],
                    ['_key' => 'industry-fact-3', 'label' => 'Policy Architecture', 'value' => 'Principal'],
                    ['_key' => 'industry-fact-4', 'label' => 'Bengaluru · Alberta', 'value' => 'India ⇄ Canada'],
                ],
            ],
        ],
        'philanthropy_intro' => [
            'name' => 'Philanthropy Introduction',
            'type' => 'philanthropy_intro',
            'sort_order' => 40,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'heading_first' => ['label' => 'Heading line one', 'type' => 'text', 'max' => 160],
                'heading_second' => ['label' => 'Heading line two', 'type' => 'text', 'max' => 160],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1800],
                'image' => ['label' => 'Section image', 'type' => 'image'],
                'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                'image_tag' => ['label' => 'Image tag', 'type' => 'text', 'max' => 80],
                'pillars' => [
                    'label' => 'Impact pillars',
                    'type' => 'repeater',
                    'max_items' => 8,
                    'fields' => [
                        'number' => ['label' => 'Number', 'type' => 'text', 'max' => 20],
                        'title' => ['label' => 'Title', 'type' => 'text', 'max' => 120],
                        'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 600],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'Governance & Public Impact',
                'heading_first' => 'Good governance and',
                'heading_second' => "good business aren't opposed.",
                'description' => "As a Trustee of the Bharat Governance Council and an advisor to ministries of the Union Government of India, the work is to strengthen India's institutional architecture — and to make sure the gains of the digital economy reach beyond metros and elite circles.",
                'image' => 'images/home/anmol-goel-philanthropy.jpg',
                'image_alt' => 'Anmol Pushjai Goel — philanthropy',
                'image_tag' => 'Governance',
                'pillars' => [
                    ['_key' => 'pillar-1', 'number' => 'I.', 'title' => 'Digital Education Access', 'description' => 'Extending digital literacy and learning to underserved and non-metro communities across India.'],
                    ['_key' => 'pillar-2', 'number' => 'II.', 'title' => 'Adaptive Policy', 'description' => 'Building more responsive, India-first policy frameworks that empower domestic entrepreneurs.'],
                    ['_key' => 'pillar-3', 'number' => 'III.', 'title' => 'AI Governance', 'description' => 'Shaping honest conversations on AI regulation, automation and digital transformation.'],
                ],
            ],
        ],
        'news' => [
            'name' => 'In the News',
            'type' => 'news',
            'sort_order' => 50,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 120],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1200],
                'ticker' => [
                    'label' => 'Ticker entries',
                    'type' => 'repeater',
                    'max_items' => 20,
                    'fields' => [
                        'outlet' => ['label' => 'Outlet', 'type' => 'text', 'max' => 120],
                        'headline' => ['label' => 'Headline', 'type' => 'text', 'max' => 200],
                    ],
                ],
                'cards' => [
                    'label' => 'News cards',
                    'type' => 'repeater',
                    'max_items' => 18,
                    'fields' => [
                        'outlet' => ['label' => 'Outlet', 'type' => 'text', 'max' => 120],
                        'kind' => ['label' => 'Content type', 'type' => 'text', 'max' => 80],
                        'title' => ['label' => 'Title', 'type' => 'textarea', 'max' => 400],
                        'category' => ['label' => 'Category', 'type' => 'text', 'max' => 80],
                        'url' => ['label' => 'Destination URL', 'type' => 'link', 'max' => 2048],
                        'image' => ['label' => 'Thumbnail', 'type' => 'image'],
                        'image_alt' => ['label' => 'Thumbnail alt text', 'type' => 'text', 'max' => 180],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'Press & Commentary',
                'heading' => 'In the news.',
                'description' => "Featured, quoted and cited — on India's AI strategy, technology governance, and a body of essays the field keeps arguing with.",
                'ticker' => [
                    ['_key' => 'ticker-1', 'outlet' => 'AI Policy Review', 'headline' => "India's place in the AI race"],
                    ['_key' => 'ticker-2', 'outlet' => 'Governance Today', 'headline' => 'Adaptive, India-first frameworks'],
                    ['_key' => 'ticker-3', 'outlet' => 'Enterprise India', 'headline' => 'Nuclear Edge & deep tech'],
                    ['_key' => 'ticker-4', 'outlet' => 'The Opinion Desk', 'headline' => 'The sociologist-entrepreneur'],
                    ['_key' => 'ticker-5', 'outlet' => 'Society & Ideas', 'headline' => 'Conformism in the age of AI'],
                    ['_key' => 'ticker-6', 'outlet' => 'Culture Weekly', 'headline' => 'The untouristy Indian'],
                ],
                'cards' => [
                    ['_key' => 'news-1', 'outlet' => 'AI Policy Review', 'kind' => 'Featured Essay', 'title' => '"We are not even in the AI race" — Goel on what India actually lacks', 'category' => 'Tech Policy', 'url' => '#', 'image' => 'images/home/ai-policy-review.jpg', 'image_alt' => ''],
                    ['_key' => 'news-2', 'outlet' => 'Governance Today', 'kind' => 'Profile', 'title' => 'Bharat Governance Council trustee on building responsive, India-first policy', 'category' => 'Governance', 'url' => '#', 'image' => null, 'image_alt' => ''],
                    ['_key' => 'news-3', 'outlet' => 'The Opinion Desk', 'kind' => 'Long Read', 'title' => 'The sociologist-entrepreneur rethinking how India adopts AI', 'category' => 'Opinion', 'url' => '#', 'image' => 'images/home/sociologist-entrepreneur.jpg', 'image_alt' => ''],
                    ['_key' => 'news-4', 'outlet' => 'Enterprise India', 'kind' => 'Company', 'title' => 'Nuclear Edge: deep-tech consulting that refuses to wait for regulation', 'category' => 'Enterprise', 'url' => '#', 'image' => 'images/home/nuclear-edge-news.jpg', 'image_alt' => ''],
                    ['_key' => 'news-5', 'outlet' => 'Society & Ideas', 'kind' => 'Essay', 'title' => '"AI is making our conformism permanent" — a provocative new argument', 'category' => 'Society', 'url' => '#', 'image' => null, 'image_alt' => ''],
                    ['_key' => 'news-6', 'outlet' => 'Culture Weekly', 'kind' => 'Commentary', 'title' => 'Who is the "untouristy Indian"? A Bourdieu-led answer', 'category' => 'Culture', 'url' => '#', 'image' => null, 'image_alt' => ''],
                ],
            ],
        ],
        'books' => [
            'name' => 'Books',
            'type' => 'books',
            'sort_order' => 60,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading_first' => ['label' => 'Heading line one', 'type' => 'text', 'max' => 120],
                'heading_second' => ['label' => 'Heading line two', 'type' => 'text', 'max' => 120],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1400],
                'image' => ['label' => 'Section image', 'type' => 'image'],
                'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                'image_tag' => ['label' => 'Image tag', 'type' => 'text', 'max' => 80],
                'items' => [
                    'label' => 'Books and essays',
                    'type' => 'repeater',
                    'max_items' => 12,
                    'fields' => [
                        'category' => ['label' => 'Cover category', 'type' => 'text', 'max' => 100],
                        'title_first' => ['label' => 'Title line one', 'type' => 'text', 'max' => 180],
                        'title_second' => ['label' => 'Title line two', 'type' => 'text', 'max' => 180],
                        'meta' => ['label' => 'Meta label', 'type' => 'text', 'max' => 140],
                        'link_label' => ['label' => 'Link label', 'type' => 'text', 'max' => 100],
                        'url' => ['label' => 'Destination URL', 'type' => 'link', 'max' => 2048],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'Selected Essays',
                'heading_first' => 'Direct, often',
                'heading_second' => 'provocative.',
                'description' => "The essays blend hard data with cultural argument — and a deliberately unfiltered voice. Three pieces map the range: India's place in the AI race, what conformism does to thought, and the sociology of the entitled traveller.",
                'image' => 'images/home/anmol-goel-books.jpg',
                'image_alt' => 'Anmol Pushjai Goel — books',
                'image_tag' => 'Essays',
                'items' => [
                    ['_key' => 'book-1', 'category' => 'AI & Policy', 'title_first' => 'We Are Not Behind in the AI Race.', 'title_second' => 'We Are Not Even in It.', 'meta' => 'Essay · AI Strategy', 'link_label' => 'Read the argument →', 'url' => '#research'],
                    ['_key' => 'book-2', 'category' => 'Society & AI', 'title_first' => 'We Are Dumb and AI Is', 'title_second' => 'Making It Permanent.', 'meta' => 'Essay · Culture', 'link_label' => 'Read the argument →', 'url' => '#research'],
                    ['_key' => 'book-3', 'category' => 'Sociology', 'title_first' => 'The Untouristy Indian.', 'title_second' => 'Who Is This Person?', 'meta' => 'Essay · Society', 'link_label' => 'Read the argument →', 'url' => '#research'],
                ],
            ],
        ],
        'research' => [
            'name' => 'Research & Publications',
            'type' => 'research',
            'sort_order' => 70,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'heading_first' => ['label' => 'Heading line one', 'type' => 'text', 'max' => 120],
                'heading_second' => ['label' => 'Heading line two', 'type' => 'text', 'max' => 120],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1400],
                'image' => ['label' => 'Section image', 'type' => 'image'],
                'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                'image_tag' => ['label' => 'Image tag', 'type' => 'text', 'max' => 80],
                'items' => [
                    'label' => 'Publications',
                    'type' => 'repeater',
                    'max_items' => 30,
                    'fields' => [
                        'tag' => ['label' => 'Topic tag', 'type' => 'text', 'max' => 80],
                        'title' => ['label' => 'Title', 'type' => 'textarea', 'max' => 400],
                        'source' => ['label' => 'Summary/source', 'type' => 'text', 'max' => 220],
                        'link_label' => ['label' => 'Link label', 'type' => 'text', 'max' => 100],
                        'url' => ['label' => 'Destination URL', 'type' => 'link', 'max' => 2048],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'Essays & Commentary',
                'heading_first' => 'The writing,',
                'heading_second' => 'in full.',
                'description' => 'A running record of essays on AI policy, Indian society and entrepreneurship — direct, data-led, and unafraid to turn the critique inward.',
                'image' => 'images/home/anmol-goel-writing.jpg',
                'image_alt' => 'Anmol Pushjai Goel — research and publications',
                'image_tag' => 'The Writing',
                'items' => [
                    ['_key' => 'publication-1', 'tag' => 'AI', 'title' => 'We Are Not Behind in the AI Race. We Are Not Even in It.', 'source' => 'On sovereign compute, frontier research & honest reckoning', 'link_label' => 'Read essay', 'url' => '#'],
                    ['_key' => 'publication-2', 'tag' => 'Society', 'title' => 'We Are Dumb and AI Is Making It Permanent.', 'source' => 'Conformism, deference & the feedback loop of LLMs', 'link_label' => 'Read essay', 'url' => '#'],
                    ['_key' => 'publication-3', 'tag' => 'Culture', 'title' => 'The Untouristy Indian. Who Is This Person?', 'source' => 'Bourdieu, inherited capital & the entitled traveller', 'link_label' => 'Read essay', 'url' => '#'],
                    ['_key' => 'publication-4', 'tag' => 'Policy', 'title' => 'Why industry must shape regulation, not wait for it', 'source' => 'On pro-business, India-first technology policy', 'link_label' => 'Read essay', 'url' => '#'],
                ],
            ],
        ],
        'voice' => [
            'name' => 'Voice & Philosophy',
            'type' => 'voice',
            'sort_order' => 80,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'author' => ['label' => 'Author', 'type' => 'text', 'max' => 140],
                'quotes' => [
                    'label' => 'Quotes',
                    'type' => 'repeater',
                    'max_items' => 15,
                    'fields' => [
                        'text' => ['label' => 'Quote', 'type' => 'textarea', 'max' => 700],
                        'accent' => ['label' => 'Gold accent sentence', 'type' => 'textarea', 'max' => 400],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'Voice & Philosophy',
                'author' => 'Anmol Pushjai Goel',
                'quotes' => [
                    ['_key' => 'quote-1', 'text' => 'Motion is not movement. You can sprint in a circle your whole life.', 'accent' => 'Pick the direction before you pick up the speed.'],
                    ['_key' => 'quote-2', 'text' => 'Everyone differentiates. Differentiation is two restaurants arguing over the menu.', 'accent' => 'Monopoly is being the only door in town.'],
                    ['_key' => 'quote-3', 'text' => 'No one wants your vision. They want to know if it makes money.', 'accent' => "Sell something first, then they'll listen to your philosophy."],
                    ['_key' => 'quote-4', 'text' => "Stop calling jugaad innovation. It's scarcity in a borrowed blazer.", 'accent' => 'Works great till it rains.'],
                ],
            ],
        ],
        'about' => [
            'name' => 'About Anmol Goel',
            'type' => 'about',
            'sort_order' => 90,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 140],
                'image_background' => ['label' => 'Background portrait layer', 'type' => 'image'],
                'image_portrait' => ['label' => 'Foreground portrait layer', 'type' => 'image'],
                'image_alt' => ['label' => 'Portrait alt text', 'type' => 'text', 'max' => 180],
                'image_tag' => ['label' => 'Vertical image tag', 'type' => 'text', 'max' => 80],
                'paragraphs' => [
                    'label' => 'Biography paragraphs',
                    'type' => 'repeater',
                    'max_items' => 12,
                    'fields' => [
                        'text' => ['label' => 'Paragraph', 'type' => 'textarea', 'max' => 1500],
                    ],
                ],
                'signature' => ['label' => 'Signature text', 'type' => 'text', 'max' => 140],
            ],
            'content' => [
                'eyebrow' => 'The Person',
                'heading' => 'Meet Anmol.',
                'image_background' => 'images/home/meet-anmol-background.jpg',
                'image_portrait' => 'images/home/anmol-pushjai-goel-meet.jpg',
                'image_alt' => 'Anmol Pushjai Goel',
                'image_tag' => 'Meet Anmol',
                'paragraphs' => [
                    ['_key' => 'about-1', 'text' => 'An entrepreneur who reads society like a text — Anmol Pushjai Goel trained not in engineering but in psychology, philosophy and sociology, across Panjab University and JNU.'],
                    ['_key' => 'about-2', 'text' => 'That interdisciplinary lens runs through everything: Nuclear Edge, his governance work, and writing that treats AI not merely as a market opportunity but as a social and ethical question for India.'],
                    ['_key' => 'about-3', 'text' => "He is both a builder within India's technology sector and one of its more unsparing internal critics — arguing that progress depends less on celebratory narratives and more on honest, structural reckoning."],
                ],
                'signature' => 'Anmol Pushjai Goel',
            ],
        ],
        'contact' => [
            'name' => 'Contact & Footer',
            'type' => 'contact',
            'sort_order' => 100,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 100],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                'primary_email' => ['label' => 'Primary email', 'type' => 'email', 'max' => 180],
                'intents' => [
                    'label' => 'Contact reasons',
                    'type' => 'repeater',
                    'max_items' => 10,
                    'fields' => [
                        'label' => ['label' => 'Label', 'type' => 'text', 'max' => 120],
                        'email' => ['label' => 'Email', 'type' => 'email', 'max' => 180],
                    ],
                ],
                'socials' => [
                    'label' => 'Social links',
                    'type' => 'repeater',
                    'max_items' => 10,
                    'fields' => [
                        'label' => ['label' => 'Platform', 'type' => 'text', 'max' => 80],
                        'url' => ['label' => 'URL', 'type' => 'link', 'max' => 2048],
                    ],
                ],
                'newsletter_label' => ['label' => 'Newsletter label', 'type' => 'text', 'max' => 100],
                'newsletter_description' => ['label' => 'Newsletter description', 'type' => 'textarea', 'max' => 800],
                'newsletter_placeholder' => ['label' => 'Email placeholder', 'type' => 'text', 'max' => 100],
                'newsletter_button' => ['label' => 'Button label', 'type' => 'text', 'max' => 80],
                'newsletter_success' => ['label' => 'Success message', 'type' => 'text', 'max' => 240],
                'newsletter_invalid' => ['label' => 'Invalid email message', 'type' => 'text', 'max' => 240],
                'copyright_name' => ['label' => 'Copyright name', 'type' => 'text', 'max' => 160],
                'strapline' => ['label' => 'Footer strapline', 'type' => 'text', 'max' => 220],
            ],
            'content' => [
                'eyebrow' => 'Get in touch',
                'heading' => "Let's start a conversation.",
                'primary_email' => 'hello@anmolpushjaigoel.com',
                'intents' => [
                    ['_key' => 'intent-1', 'label' => 'Media & press', 'email' => 'press@anmolpushjaigoel.com'],
                    ['_key' => 'intent-2', 'label' => 'Speaking', 'email' => 'speaking@anmolpushjaigoel.com'],
                    ['_key' => 'intent-3', 'label' => 'Business & collaboration', 'email' => 'hello@anmolpushjaigoel.com'],
                ],
                'socials' => [
                    ['_key' => 'social-1', 'label' => 'LinkedIn', 'url' => '#'],
                    ['_key' => 'social-2', 'label' => 'X / Twitter', 'url' => '#'],
                    ['_key' => 'social-3', 'label' => 'Instagram', 'url' => '#'],
                ],
                'newsletter_label' => 'The Newsletter',
                'newsletter_description' => 'Occasional letters on AI policy, technology and Indian society — direct, and without the usual hedging.',
                'newsletter_placeholder' => 'your@email.com',
                'newsletter_button' => 'Subscribe',
                'newsletter_success' => 'Thank you — you are on the list.',
                'newsletter_invalid' => 'Please enter a valid email address.',
                'copyright_name' => 'Anmol Pushjai Goel',
                'strapline' => 'Entrepreneur · Tech & AI Policy Voice · Author',
            ],
        ],
    ],

    'custom_section' => [
        'name' => 'Custom Content Section',
        'type' => 'custom_content',
        'fields' => [
            'anchor' => ['label' => 'Section anchor', 'type' => 'slug', 'max' => 80],
            'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
            'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
            'body' => ['label' => 'Body', 'type' => 'textarea', 'max' => 4000],
            'image' => ['label' => 'Image', 'type' => 'image'],
            'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
            'theme' => [
                'label' => 'Theme',
                'type' => 'select',
                'options' => ['light' => 'Light', 'dark' => 'Dark'],
            ],
            'button_label' => ['label' => 'Button label', 'type' => 'text', 'max' => 100],
            'button_url' => ['label' => 'Button URL', 'type' => 'link', 'max' => 2048],
        ],
        'content' => [
            'anchor' => '',
            'eyebrow' => 'New Section',
            'heading' => 'Section heading',
            'body' => 'Add the section content here.',
            'image' => null,
            'image_alt' => '',
            'theme' => 'light',
            'button_label' => '',
            'button_url' => '',
        ],
    ],
];
