<?php

return [
    'page' => [
        'title' => 'Anmol Pushjai Goel',
        'seo_title' => 'Anmol Pushjai Goel · Entrepreneur, Tech and AI Policy Expert, Author',
        'meta_description' => 'Anmol Pushjai Goel is an Indian tech policy expert and entrepreneur, Founder and CEO of Nuclear Edge, a deep technology and business consulting firm.',
        'og_image' => 'images/home/redesign-hero-portrait.jpg',
    ],

    'sections' => [
        'hero' => [
            'name' => 'Hero',
            'type' => 'hero',
            'sort_order' => 10,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 180],
                'title_first' => ['label' => 'Title line one', 'type' => 'text', 'max' => 100],
                'title_second' => ['label' => 'Title line two', 'type' => 'text', 'max' => 100],
                'description' => ['label' => 'Introduction', 'type' => 'textarea', 'max' => 1200],
                'description_secondary' => ['label' => 'Secondary introduction', 'type' => 'textarea', 'max' => 800],
                'primary_button_label' => ['label' => 'Primary button label', 'type' => 'text', 'max' => 80],
                'primary_button_url' => ['label' => 'Primary button destination', 'type' => 'link', 'max' => 2048],
                'secondary_button_label' => ['label' => 'Secondary button label', 'type' => 'text', 'max' => 80],
                'secondary_button_url' => ['label' => 'Secondary button destination', 'type' => 'link', 'max' => 2048],
                'image' => ['label' => 'Portrait', 'type' => 'image'],
                'image_alt' => ['label' => 'Portrait alt text', 'type' => 'text', 'max' => 180],
            ],
            'content' => [
                'eyebrow' => 'Entrepreneur · Technology and AI policy · Author',
                'title_first' => 'Anmol Pushjai',
                'title_second' => 'Goel',
                'description' => 'A prominent Indian entrepreneur, technology policy expert, and the Founder and Chief Executive of <a href="https://www.aninews.in/news/business/nuclear-edge-best-it-company-revenue-networth-directors-anmol-pushjai-goel-prominent-indian-entrepreneur-and-ai-policy-expert20260622180345/" target="_blank" rel="noopener">Nuclear Edge</a>. He serves as a Trustee of the <a href="https://m.thewire.in/article/ptiprnews/anmol-pushjai-goel-prominent-indian-entrepreneur-and-tech-policy-expert-redefining-indias-ai-agenda/amp" target="_blank" rel="noopener">Bharat Governance Council</a> and holds advisory board positions across multiple ministries in the Indian Union Government.',
                'description_secondary' => 'He is known for his advocacy on India’s artificial intelligence and automation policy, with a focus on domestic business empowerment and inclusive technological growth.',
                'primary_button_label' => 'Selected writing',
                'primary_button_url' => '#essays',
                'secondary_button_label' => 'Get in touch',
                'secondary_button_url' => '#connect',
                'image' => 'images/home/redesign-hero-portrait.jpg',
                'image_alt' => 'Portrait of Anmol Pushjai Goel',
            ],
        ],
        'creed' => [
            'name' => 'Positioning Strip',
            'type' => 'creed',
            'sort_order' => 20,
            'admin_hidden' => true,
            'fields' => [],
            'content' => [
                'statement' => 'A single thread runs through the company, the policy work and the writing —',
                'accent' => 'conviction, put to work.',
                'highlights' => [
                    ['_key' => 'creed-1', 'title' => 'Nuclear Edge', 'description' => 'Founder & CEO · Deep-tech consulting'],
                    ['_key' => 'creed-2', 'title' => 'Bharat', 'description' => 'Trustee, Bharat Governance Council'],
                    ['_key' => 'creed-3', 'title' => 'Union Govt.', 'description' => 'Advisory & board roles, ministries'],
                    ['_key' => 'creed-4', 'title' => 'Psych · Phil · Soc', 'description' => 'An interdisciplinary lens on technology'],
                ],
            ],
        ],
        'industries_intro' => [
            'name' => 'Industries Introduction',
            'type' => 'industries_intro',
            'sort_order' => 30,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading_first' => ['label' => 'Heading line one', 'type' => 'text', 'max' => 140],
                'heading_second' => ['label' => 'Heading line two', 'type' => 'text', 'max' => 140],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1800],
                'image' => ['label' => 'Section image', 'type' => 'image'],
                'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                'image_tag' => ['label' => 'Image tag', 'type' => 'text', 'max' => 80],
                'facts' => [
                    'label' => 'Company facts',
                    'type' => 'repeater',
                    'max_items' => 12,
                    'fields' => [
                        'label' => ['label' => 'Focus', 'type' => 'text', 'max' => 180],
                        'value' => ['label' => 'Role/value', 'type' => 'text', 'max' => 140],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'Nuclear Edge',
                'heading_first' => 'Deep technology',
                'heading_second' => 'consulting.',
                'description' => 'Headquartered in Bengaluru, with a presence in Alberta, Canada. The firm advises enterprises and institutions on deep technology, digital transformation and technology policy.',
                'image' => 'images/home/redesign-company-band.jpg',
                'image_alt' => 'Nuclear Edge office environment',
                'image_tag' => '',
                'facts' => [
                    ['_key' => 'industry-fact-1', 'label' => 'Deep tech and digital transformation', 'value' => 'Founder and CEO'],
                    ['_key' => 'industry-fact-2', 'label' => 'Blockchain and enterprise strategy', 'value' => 'Architect'],
                    ['_key' => 'industry-fact-3', 'label' => 'Policy architecture', 'value' => 'Principal'],
                ],
            ],
        ],
        'philanthropy_intro' => [
            'name' => 'Philanthropy Introduction',
            'type' => 'philanthropy_intro',
            'sort_order' => 40,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'heading_first' => ['label' => 'Heading line one', 'type' => 'text', 'max' => 160],
                'heading_second' => ['label' => 'Heading line two', 'type' => 'text', 'max' => 160],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1800],
                'image' => ['label' => 'Section image', 'type' => 'image'],
                'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                'image_tag' => ['label' => 'Image tag', 'type' => 'text', 'max' => 80],
                'pillars' => [
                    'label' => 'Impact pillars',
                    'type' => 'repeater',
                    'max_items' => 8,
                    'fields' => [
                        'number' => ['label' => 'Number', 'type' => 'text', 'max' => 20],
                        'title' => ['label' => 'Title', 'type' => 'text', 'max' => 120],
                        'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 600],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'Governance and public impact',
                'heading_first' => 'Institutions, policy and',
                'heading_second' => 'public impact.',
                'description' => 'Trustee of the Bharat Governance Council and an advisor to ministries of the Union Government of India. The work centres on digital access, adaptive regulation and the governance of artificial intelligence.',
                'image' => 'images/home/anmol-goel-philanthropy.jpg',
                'image_alt' => 'Anmol Pushjai Goel — philanthropy',
                'image_tag' => 'Governance',
                'pillars' => [
                    ['_key' => 'pillar-1', 'number' => 'I', 'title' => 'Digital education access', 'description' => 'Extending digital literacy and learning to underserved communities beyond the metros.'],
                    ['_key' => 'pillar-2', 'number' => 'II', 'title' => 'Adaptive policy', 'description' => 'Responsive, India first frameworks that give domestic enterprise room to build.'],
                    ['_key' => 'pillar-3', 'number' => 'III', 'title' => 'AI governance', 'description' => 'Regulation, automation and the responsible adoption of artificial intelligence.'],
                ],
            ],
        ],
        'news' => [
            'name' => 'In the News',
            'type' => 'news',
            'sort_order' => 50,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 120],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1200],
                'coverage' => [
                    'label' => 'Homepage press cards',
                    'type' => 'repeater',
                    'max_items' => 12,
                    'fields' => [
                        'outlet' => ['label' => 'Outlet', 'type' => 'text', 'max' => 140],
                        'title' => ['label' => 'Headline', 'type' => 'text', 'max' => 220],
                        'date' => ['label' => 'Link label', 'type' => 'text', 'max' => 80],
                        'url' => ['label' => 'Destination URL', 'type' => 'link', 'max' => 2048],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'Press',
                'heading' => 'In the news.',
                'description' => "Featured, quoted and cited — on India's AI strategy, technology governance, and a body of essays the field keeps arguing with.",
                'coverage' => [
                    ['_key' => 'home-press-1', 'outlet' => 'AI Policy Review', 'title' => 'India’s position in the AI race', 'date' => 'Read feature', 'url' => '#'],
                    ['_key' => 'home-press-2', 'outlet' => 'Governance Today', 'title' => 'Adaptive, India first frameworks', 'date' => 'Read feature', 'url' => '#'],
                    ['_key' => 'home-press-3', 'outlet' => 'Enterprise India', 'title' => 'Nuclear Edge and deep technology', 'date' => 'Read feature', 'url' => '#'],
                    ['_key' => 'home-press-4', 'outlet' => 'The Opinion Desk', 'title' => 'Governance beyond the metros', 'date' => 'Read feature', 'url' => '#'],
                    ['_key' => 'home-press-5', 'outlet' => 'Society & Ideas', 'title' => 'Artificial intelligence and society', 'date' => 'Read feature', 'url' => '#'],
                    ['_key' => 'home-press-6', 'outlet' => 'Culture Weekly', 'title' => 'Class, capital and taste', 'date' => 'Read feature', 'url' => '#'],
                ],
            ],
        ],
        'books' => [
            'name' => 'Books',
            'type' => 'books',
            'sort_order' => 60,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading_first' => ['label' => 'Heading line one', 'type' => 'text', 'max' => 120],
                'heading_second' => ['label' => 'Heading line two', 'type' => 'text', 'max' => 120],
                'description' => ['label' => 'Image note', 'type' => 'textarea', 'max' => 1400],
                'lede' => ['label' => 'Section lede', 'type' => 'textarea', 'max' => 1000],
                'image' => ['label' => 'Section image', 'type' => 'image'],
                'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                'image_tag' => ['label' => 'Image tag', 'type' => 'text', 'max' => 80],
                'items' => [
                    'label' => 'Books and essays',
                    'type' => 'repeater',
                    'max_items' => 12,
                    'fields' => [
                        'category' => ['label' => 'Cover category', 'type' => 'text', 'max' => 100],
                        'title_first' => ['label' => 'Title line one', 'type' => 'text', 'max' => 180],
                        'title_second' => ['label' => 'Title line two', 'type' => 'text', 'max' => 180],
                        'meta' => ['label' => 'Meta label', 'type' => 'text', 'max' => 140],
                        'link_label' => ['label' => 'Link label', 'type' => 'text', 'max' => 100],
                        'url' => ['label' => 'Destination URL', 'type' => 'link', 'max' => 2048],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'Selected writing',
                'heading_first' => 'Essays and',
                'heading_second' => 'commentary.',
                'description' => 'Essays on artificial intelligence, technology policy and Indian society.',
                'lede' => 'Long form writing on technology policy, enterprise and the society that receives them.',
                'image' => 'images/home/redesign-writing-office.jpg',
                'image_alt' => 'Anmol Pushjai Goel at the Nuclear Edge office',
                'image_tag' => '',
                'items' => [
                    ['_key' => 'book-1', 'category' => 'Artificial intelligence', 'title_first' => 'India’s position in the', 'title_second' => 'global AI race', 'meta' => 'On sovereign compute, frontier research and an honest reckoning.', 'link_label' => 'Read', 'url' => '#'],
                    ['_key' => 'book-2', 'category' => 'Society', 'title_first' => 'Artificial intelligence and', 'title_second' => 'the cost of conformity', 'meta' => 'Deference, feedback loops and the language models we defer to.', 'link_label' => 'Read', 'url' => '#'],
                    ['_key' => 'book-3', 'category' => 'Culture', 'title_first' => 'Class, capital and', 'title_second' => 'the Indian traveller', 'meta' => 'Inherited advantage and the language of taste.', 'link_label' => 'Read', 'url' => '#'],
                    ['_key' => 'book-4', 'category' => 'Policy', 'title_first' => 'Why industry should help', 'title_second' => 'shape regulation', 'meta' => 'A pro business, India first approach to technology policy.', 'link_label' => 'Read', 'url' => '#'],
                ],
            ],
        ],
        'research' => [
            'name' => 'Research & Publications',
            'type' => 'research',
            'sort_order' => 70,
            'admin_hidden' => true,
            'fields' => [],
            'content' => [
                'eyebrow' => 'Essays & Commentary',
                'heading_first' => 'The writing,',
                'heading_second' => 'in full.',
                'description' => 'A running record of essays on AI policy, Indian society and entrepreneurship — direct, data-led, and unafraid to turn the critique inward.',
                'image' => 'images/home/anmol-goel-writing.jpg',
                'image_alt' => 'Anmol Pushjai Goel — research and publications',
                'image_tag' => 'The Writing',
                'items' => [
                    ['_key' => 'publication-1', 'tag' => 'AI', 'title' => 'We Are Not Behind in the AI Race. We Are Not Even in It.', 'source' => 'On sovereign compute, frontier research & honest reckoning', 'link_label' => 'Read essay', 'url' => '#'],
                    ['_key' => 'publication-2', 'tag' => 'Society', 'title' => 'We Are Dumb and AI Is Making It Permanent.', 'source' => 'Conformism, deference & the feedback loop of LLMs', 'link_label' => 'Read essay', 'url' => '#'],
                    ['_key' => 'publication-3', 'tag' => 'Culture', 'title' => 'The Untouristy Indian. Who Is This Person?', 'source' => 'Bourdieu, inherited capital & the entitled traveller', 'link_label' => 'Read essay', 'url' => '#'],
                    ['_key' => 'publication-4', 'tag' => 'Policy', 'title' => 'Why industry must shape regulation, not wait for it', 'source' => 'On pro-business, India-first technology policy', 'link_label' => 'Read essay', 'url' => '#'],
                ],
            ],
        ],
        'voice' => [
            'name' => 'Voice & Philosophy',
            'type' => 'voice',
            'sort_order' => 80,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'author' => ['label' => 'Author', 'type' => 'text', 'max' => 140],
                'image' => ['label' => 'Portrait', 'type' => 'image'],
                'image_alt' => ['label' => 'Portrait alt text', 'type' => 'text', 'max' => 180],
                'quotes' => [
                    'label' => 'Quotes',
                    'type' => 'repeater',
                    'max_items' => 15,
                    'fields' => [
                        'text' => ['label' => 'Quote', 'type' => 'textarea', 'max' => 700],
                        'accent' => ['label' => 'Muted accent phrase', 'type' => 'textarea', 'max' => 400],
                        'subtext' => ['label' => 'Supporting line', 'type' => 'textarea', 'max' => 500],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'In his own words',
                'author' => 'Anmol Pushjai Goel',
                'image' => 'images/home/redesign-voice-portrait.png',
                'image_alt' => 'Anmol Pushjai Goel speaking on stage with a headset microphone',
                'quotes' => [
                    ['_key' => 'quote-1', 'text' => 'Good governance and good business', 'accent' => 'are not opposed.', 'subtext' => 'The gains of the digital economy have to reach beyond the metros to count.'],
                    ['_key' => 'quote-2', 'text' => 'Industry should help shape regulation,', 'accent' => 'not wait for it.', 'subtext' => 'With ambition, and with accountability.'],
                    ['_key' => 'quote-3', 'text' => 'Sovereign compute and frontier research', 'accent' => 'are not slogans.', 'subtext' => 'They are line items, and they are decided years before they are visible.'],
                ],
            ],
        ],
        'about' => [
            'name' => 'About Anmol Goel',
            'type' => 'about',
            'sort_order' => 90,
            'admin_hidden' => true,
            'fields' => [],
            'content' => [
                'eyebrow' => 'The Person',
                'heading' => 'Meet Anmol.',
                'image_background' => 'images/home/meet-anmol-background.jpg',
                'image_portrait' => 'images/home/anmol-pushjai-goel-meet.jpg',
                'image_alt' => 'Anmol Pushjai Goel',
                'image_tag' => 'Meet Anmol',
                'paragraphs' => [
                    ['_key' => 'about-1', 'text' => 'An entrepreneur who reads society like a text — Anmol Pushjai Goel trained not in engineering but in psychology, philosophy and sociology, across Panjab University and JNU.'],
                    ['_key' => 'about-2', 'text' => 'That interdisciplinary lens runs through everything: Nuclear Edge, his governance work, and writing that treats AI not merely as a market opportunity but as a social and ethical question for India.'],
                    ['_key' => 'about-3', 'text' => "He is both a builder within India's technology sector and one of its more unsparing internal critics — arguing that progress depends less on celebratory narratives and more on honest, structural reckoning."],
                ],
                'signature' => 'Anmol Pushjai Goel',
            ],
        ],
        'contact' => [
            'name' => 'Contact & Footer',
            'type' => 'contact',
            'sort_order' => 100,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 100],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                'primary_email' => ['label' => 'Primary email', 'type' => 'email', 'max' => 180],
                'footer_mark' => ['label' => 'Footer mark', 'type' => 'image'],
                'footer_mark_alt' => ['label' => 'Footer mark alt text', 'type' => 'text', 'max' => 180],
                'location_primary' => ['label' => 'Primary location', 'type' => 'text', 'max' => 120],
                'location_secondary' => ['label' => 'Secondary location', 'type' => 'text', 'max' => 120],
                'footer_locations' => ['label' => 'Footer locations line', 'type' => 'text', 'max' => 180],
                'explore_label' => ['label' => 'Explore label', 'type' => 'text', 'max' => 100],
                'intents' => [
                    'label' => 'Contact reasons',
                    'type' => 'repeater',
                    'max_items' => 10,
                    'fields' => [
                        'label' => ['label' => 'Label', 'type' => 'text', 'max' => 120],
                        'email' => ['label' => 'Email', 'type' => 'email', 'max' => 180],
                    ],
                ],
                'socials' => [
                    'label' => 'Social links',
                    'type' => 'repeater',
                    'max_items' => 10,
                    'fields' => [
                        'label' => ['label' => 'Platform', 'type' => 'text', 'max' => 80],
                        'url' => ['label' => 'URL', 'type' => 'link', 'max' => 2048],
                    ],
                ],
                'newsletter_label' => ['label' => 'Newsletter label', 'type' => 'text', 'max' => 100],
                'newsletter_description' => ['label' => 'Newsletter description', 'type' => 'textarea', 'max' => 800],
                'newsletter_placeholder' => ['label' => 'Email placeholder', 'type' => 'text', 'max' => 100],
                'newsletter_button' => ['label' => 'Button label', 'type' => 'text', 'max' => 80],
                'newsletter_success' => ['label' => 'Success message', 'type' => 'text', 'max' => 240],
                'newsletter_invalid' => ['label' => 'Invalid email message', 'type' => 'text', 'max' => 240],
                'copyright_name' => ['label' => 'Copyright name', 'type' => 'text', 'max' => 160],
                'strapline' => ['label' => 'Footer strapline', 'type' => 'text', 'max' => 220],
            ],
            'content' => [
                'eyebrow' => 'Get in touch',
                'heading' => "Let's start a conversation.",
                'primary_email' => 'Ap@NuclearEdge.com',
                'footer_mark' => 'images/home/redesign-footer-mark.png',
                'footer_mark_alt' => 'APG',
                'location_primary' => 'Bengaluru',
                'location_secondary' => 'Alberta, Canada',
                'footer_locations' => 'Bengaluru · Alberta',
                'explore_label' => 'Explore',
                'intents' => [
                    ['_key' => 'intent-1', 'label' => 'Media & press', 'email' => 'press@anmolpushjaigoel.com'],
                    ['_key' => 'intent-2', 'label' => 'Speaking', 'email' => 'speaking@anmolpushjaigoel.com'],
                    ['_key' => 'intent-3', 'label' => 'Business & collaboration', 'email' => 'hello@anmolpushjaigoel.com'],
                ],
                'socials' => [
                    ['_key' => 'social-1', 'label' => 'Industries', 'url' => '#industries'],
                    ['_key' => 'social-2', 'label' => 'In the News', 'url' => '#press'],
                    ['_key' => 'social-3', 'label' => 'Research & Publications', 'url' => '#research'],
                    ['_key' => 'social-4', 'label' => 'LinkedIn', 'url' => 'https://www.linkedin.com/in/anmol-pushjai-goel/'],
                ],
                'newsletter_label' => 'Newsletter',
                'newsletter_description' => 'Occasional letters on technology policy, enterprise and Indian society.',
                'newsletter_placeholder' => 'Your email address',
                'newsletter_button' => 'Subscribe',
                'newsletter_success' => 'Thank you. You are subscribed.',
                'newsletter_invalid' => 'Please enter a valid email address.',
                'copyright_name' => 'Anmol Pushjai Goel',
                'strapline' => 'Entrepreneur · Technology & AI Policy · Author',
            ],
        ],
    ],

    'custom_section' => [
        'name' => 'Custom Content Section',
        'type' => 'custom_content',
        'fields' => [
            'anchor' => ['label' => 'Section anchor', 'type' => 'slug', 'max' => 80],
            'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
            'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
            'body' => ['label' => 'Body', 'type' => 'textarea', 'max' => 4000],
            'image' => ['label' => 'Image', 'type' => 'image'],
            'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
            'theme' => [
                'label' => 'Theme',
                'type' => 'select',
                'options' => ['light' => 'Light', 'dark' => 'Dark'],
            ],
            'button_label' => ['label' => 'Button label', 'type' => 'text', 'max' => 100],
            'button_url' => ['label' => 'Button URL', 'type' => 'link', 'max' => 2048],
        ],
        'content' => [
            'anchor' => '',
            'eyebrow' => 'New Section',
            'heading' => 'Section heading',
            'body' => 'Add the section content here.',
            'image' => null,
            'image_alt' => '',
            'theme' => 'light',
            'button_label' => '',
            'button_url' => '',
        ],
    ],
];
