<?php

return [
    'page' => [
        'title' => 'Industries',
        'seo_title' => 'Industries — Anmol Pushjai Goel · Nuclear Edge',
        'meta_description' => 'Where Anmol Pushjai Goel invests, and why — durable businesses with moats, capable people and prices that leave room for error, across India with conviction in the North.',
        'og_image' => 'images/industries/technology.jpg',
    ],

    'sections' => [
        'hero' => [
            'name' => 'Hero',
            'type' => 'hero',
            'sort_order' => 10,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 180],
                'title_first' => ['label' => 'Title line one', 'type' => 'text', 'max' => 140],
                'title_second' => ['label' => 'Title line two', 'type' => 'text', 'max' => 140],
                'description' => ['label' => 'Introduction', 'type' => 'textarea', 'max' => 1800],
                'stats' => [
                    'label' => 'Statistics',
                    'type' => 'repeater',
                    'max_items' => 6,
                    'fields' => [
                        'value' => ['label' => 'Value', 'type' => 'text', 'max' => 40],
                        'label' => ['label' => 'Label', 'type' => 'text', 'max' => 100],
                    ],
                ],
                'scroll_label' => ['label' => 'Scroll label', 'type' => 'text', 'max' => 80],
                'background_image' => ['label' => 'Background image', 'type' => 'image'],
                'background_alt' => ['label' => 'Background image alt text', 'type' => 'text', 'max' => 180],
            ],
            'content' => [
                'eyebrow' => 'The Portfolio · Nuclear Edge',
                'title_first' => 'Where we invest,',
                'title_second' => 'and why.',
                'description' => 'We buy durable businesses, run by capable people, at prices that leave room for error — and we hold them for the long arc of their growth. We invest across India, with a particular conviction in the North we know best.',
                'stats' => [
                    ['_key' => 'hero-stat-1', 'value' => '11', 'label' => 'Industries'],
                    ['_key' => 'hero-stat-2', 'value' => '10-yr', 'label' => 'The test we apply'],
                    ['_key' => 'hero-stat-3', 'value' => 'North', 'label' => 'India conviction'],
                ],
                'scroll_label' => 'The Philosophy',
                'background_image' => 'images/industries/hero-space.jpg',
                'background_alt' => '',
            ],
        ],
        'creed' => [
            'name' => 'Investment Philosophy',
            'type' => 'creed',
            'sort_order' => 20,
            'fields' => [
                'statement_before' => ['label' => 'Statement before accent', 'type' => 'textarea', 'max' => 500],
                'statement_accent' => ['label' => 'Gold accent text', 'type' => 'text', 'max' => 200],
                'statement_after' => ['label' => 'Statement after accent', 'type' => 'textarea', 'max' => 500],
                'principles' => [
                    'label' => 'Principles',
                    'type' => 'repeater',
                    'max_items' => 8,
                    'fields' => [
                        'title' => ['label' => 'Title', 'type' => 'text', 'max' => 120],
                        'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 400],
                    ],
                ],
                'background_image' => ['label' => 'Background image', 'type' => 'image'],
                'background_alt' => ['label' => 'Background image alt text', 'type' => 'text', 'max' => 180],
            ],
            'content' => [
                'statement_before' => 'Understand the business before the stock. Prize the',
                'statement_accent' => 'moat over the momentum.',
                'statement_after' => 'And let time do the heavy lifting.',
                'principles' => [
                    ['_key' => 'principle-1', 'title' => 'Circle of competence', 'description' => 'Old-economy cash and the digital frontier, deliberately chosen'],
                    ['_key' => 'principle-2', 'title' => 'The one question', 'description' => 'Will this business be earning more, ten years from now?'],
                    ['_key' => 'principle-3', 'title' => 'Geography', 'description' => 'All of India, with an on-the-ground North-India edge'],
                    ['_key' => 'principle-4', 'title' => 'The horizon', 'description' => 'Long-term owners — not traders of tickers'],
                ],
                'background_image' => 'images/industries/creed-buildings.jpg',
                'background_alt' => '',
            ],
        ],
        'portfolio' => [
            'name' => 'Portfolio Introduction',
            'type' => 'portfolio',
            'sort_order' => 30,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1600],
                'tile_link_label' => ['label' => 'Tile link label', 'type' => 'text', 'max' => 80],
                'background_image' => ['label' => 'Background image', 'type' => 'image'],
                'background_alt' => ['label' => 'Background image alt text', 'type' => 'text', 'max' => 180],
            ],
            'content' => [
                'eyebrow' => 'The Sectors',
                'heading' => 'Where the capital sits.',
                'description' => 'From silicon to dairy to timber — eleven industries, chosen not by sector label but by one shared test: a business that will still be earning, and earning more, a decade from now. Tap any to read the thesis.',
                'tile_link_label' => 'View thesis →',
                'background_image' => 'images/industries/portfolio-data-centre.jpg',
                'background_alt' => '',
            ],
        ],
        'closing' => [
            'name' => 'Closing Statement',
            'type' => 'closing',
            'sort_order' => 40,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1800],
                'button_label' => ['label' => 'Button label', 'type' => 'text', 'max' => 100],
                'button_url' => ['label' => 'Button destination', 'type' => 'link', 'max' => 2048],
                'background_image' => ['label' => 'Background image', 'type' => 'image'],
                'background_alt' => ['label' => 'Background image alt text', 'type' => 'text', 'max' => 180],
            ],
            'content' => [
                'eyebrow' => 'The Common Thread',
                'heading' => 'Understand. Trust. Respect. Protect.',
                'description' => 'Across every industry we touch, the test is the same — a business we can understand, a moat we can trust, a management we can respect, and a price that protects us if we are wrong. We partner with businesses, and the people who build them, for the years it takes for great companies to become greater.',
                'button_label' => 'Start a conversation',
                'button_url' => '#contact',
                'background_image' => 'images/industries/closing-policy.jpg',
                'background_alt' => '',
            ],
        ],
        'contact' => [
            'name' => 'Contact & Footer',
            'type' => 'contact',
            'sort_order' => 50,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 160],
                'email' => ['label' => 'Contact email', 'type' => 'email', 'max' => 254],
                'company_label' => ['label' => 'Company label', 'type' => 'text', 'max' => 100],
                'description' => ['label' => 'Company description', 'type' => 'textarea', 'max' => 1200],
                'linkedin_url' => ['label' => 'LinkedIn URL', 'type' => 'link', 'max' => 2048],
                'twitter_url' => ['label' => 'X / Twitter URL', 'type' => 'link', 'max' => 2048],
                'copyright_name' => ['label' => 'Copyright name', 'type' => 'text', 'max' => 160],
                'footer_role' => ['label' => 'Footer role line', 'type' => 'text', 'max' => 240],
            ],
            'content' => [
                'eyebrow' => 'Investment & collaboration',
                'heading' => 'Let’s talk capital.',
                'email' => 'invest@anmolpushjaigoel.com',
                'company_label' => 'Nuclear Edge',
                'description' => 'Deep-tech consulting & a long-horizon portfolio across technology, energy, food, logistics, materials, education and media — with conviction in North India.',
                'linkedin_url' => '#',
                'twitter_url' => '#',
                'copyright_name' => 'Anmol Pushjai Goel. All rights reserved.',
                'footer_role' => 'Entrepreneur · Investor · Tech & AI Policy Voice',
            ],
        ],
    ],

    'items' => [
        [
            'name' => 'Technology',
            'tag' => 'Compute · Platforms · Pricing Power',
            'image' => 'images/industries/technology.jpg',
            'image_alt' => 'Technology',
            'body_before' => 'The compounding engine of the modern economy — and India is no longer just its back office, but a builder of products and platforms. We back technology businesses with genuine pricing power: defensible IP, sticky customers, and switching costs that widen the moat each year. We favour companies whose advantage is',
            'body_accent' => 'structural rather than sentimental',
            'body_after' => ', funded by their own cash rather than the next round of capital.',
            'pull_quote' => 'Wary of fashion, fond of fundamentals.',
            'facts' => ['Defensible IP', 'Self-funded growth'],
        ],
        [
            'name' => 'IT Services',
            'tag' => 'Delivery Scale · Client Trust',
            'image' => 'images/industries/it-services.jpg',
            'image_alt' => 'IT Services',
            'body_before' => 'One of India’s truest moats — built on talent depth, delivery scale, and decades of client trust competitors cannot replicate overnight. We look for firms with high client retention, diversified revenue, and the discipline to',
            'body_accent' => 'move up the value chain',
            'body_after' => 'from labour arbitrage toward outcomes, automation and domain expertise.',
            'pull_quote' => 'Durable, cash-rich franchises with long reinvestment runways.',
            'facts' => ['Noida · Gurugram corridors', 'High client retention'],
        ],
        [
            'name' => 'Data Centres',
            'tag' => 'Digital Infrastructure · Real Assets',
            'image' => 'images/industries/data-centres.jpg',
            'image_alt' => 'Data Centres',
            'body_before' => 'Every app, transaction and AI model has to live somewhere — increasingly on Indian soil, driven by data localisation, cloud adoption and surging digital consumption. Data centres are the',
            'body_accent' => 'toll roads of the digital age',
            'body_after' => ': capital-intensive to build, blessed with long contracts, recurring revenue and high barriers to entry.',
            'pull_quote' => 'A multi-decade compounding theme in real infrastructure.',
            'facts' => ['Long-tenor contracts', 'Power & land advantage'],
        ],
        [
            'name' => 'Petroleum',
            'tag' => 'Distribution · Storage · Logistics',
            'image' => 'images/industries/petroleum.jpg',
            'image_alt' => 'Petroleum',
            'body_before' => 'Energy is the bloodstream of an industrialising economy, and petroleum remains foundational to India’s transport, manufacturing and rural growth. We favour businesses with control over distribution, strong storage and logistics, and resilient margins through the cycle — a',
            'body_accent' => 'durable, cash-generative position',
            'body_after' => 'rather than a bet on the price of a barrel.',
            'pull_quote' => 'We approach the sector with the patience it demands.',
            'facts' => ['North India consumption belt', 'Throughput & infrastructure'],
        ],
        [
            'name' => 'Milk & Dairy',
            'tag' => 'Procurement · Cold Chain · Brand',
            'image' => 'images/industries/milk-dairy.jpg',
            'image_alt' => 'Milk and Dairy',
            'body_before' => 'One of the great recurring-revenue businesses hidden in plain sight — a daily, non-discretionary purchase in nearly every Indian household. North India is the heartland of Indian milk. We invest in strong procurement networks, cold-chain capability and brand loyalty that turns a commodity into a moat — companies that',
            'body_accent' => 'earn a little, every day, from millions of customers',
            'body_after' => ', and reinvest it for decades.',
            'pull_quote' => 'The closest thing in food to a perpetual annuity.',
            'facts' => ['Punjab · Haryana · UP · Rajasthan', 'Farmer networks'],
        ],
        [
            'name' => 'Transportation & Logistics',
            'tag' => 'Freight Corridors · Route Density',
            'image' => 'images/industries/transportation-logistics.jpg',
            'image_alt' => 'Transportation and Logistics',
            'body_before' => 'As goods move, value moves with them — and India’s logistics backbone is being rebuilt at historic scale. We back asset-smart operators along the country’s freight corridors, with the Delhi-NCR hub and the region’s arterial highways among the densest goods movement in India — operators with the discipline to',
            'body_accent' => 'convert volume into consistent free cash flow',
            'body_after' => ', not commoditised competition.',
            'pull_quote' => 'The arteries every other industry quietly relies on.',
            'facts' => ['Delhi-NCR freight hub', 'Repeat customers'],
        ],
        [
            'name' => 'Timber & Wood',
            'tag' => 'Import / Export · Processing',
            'image' => 'images/industries/timber-wood.jpg',
            'image_alt' => 'Timber and Wood',
            'body_before' => 'Few associate North India with global trade flows — yet Yamunanagar in Haryana is the plywood and timber capital of the country, and India’s construction and furniture demand keeps wood in perpetual short supply. A classic trading and processing business: supplier relationships, working-capital discipline, port logistics from Kandla to the heartland.',
            'body_accent' => 'An old business done well',
            'body_after' => '— steady margins, real assets.',
            'pull_quote' => 'Demand tied directly to India’s housing and infrastructure growth.',
            'facts' => ['Yamunanagar · Kandla port', 'Working-capital discipline'],
        ],
        [
            'name' => 'Education',
            'tag' => 'Institutions · Brands · Outcomes',
            'image' => 'images/industries/education.jpg',
            'image_alt' => 'Education',
            'body_before' => 'The most defensible business in any aspiring economy — driven by relentless demand, deep trust, and pricing power that compounds with reputation. India’s young population and North India’s standing as a centre of learning — from Delhi to Chandigarh to the coaching capital of Kota — create a decade-long tailwind. We back brands and outcomes that turn a single campus into a',
            'body_accent' => 'generational franchise',
            'body_after' => '.',
            'pull_quote' => 'Reputation compounds; it does not depreciate.',
            'facts' => ['Delhi · Chandigarh · Kota', 'Demonstrated outcomes'],
        ],
        [
            'name' => 'EdTech',
            'tag' => 'Digital Learning · Selective',
            'image' => 'images/industries/edtech.jpg',
            'image_alt' => 'EdTech',
            'body_before' => 'EdTech extends quality education from the metros to the smallest towns, where India’s appetite for learning meets its smartphone penetration. We invest selectively and with discipline — mindful that not every fast-growing platform earns its keep. We look for unit economics that work and retention that proves real value, backing the rare businesses building',
            'body_accent' => 'a moat, not just a user count',
            'body_after' => '.',
            'pull_quote' => 'The opportunity is enormous; our standard is unforgiving.',
            'facts' => ['Unit-economics first', 'Real retention'],
        ],
        [
            'name' => 'Production Houses',
            'tag' => 'Content · IP · Libraries',
            'image' => 'images/industries/production-houses.jpg',
            'image_alt' => 'Production Houses',
            'body_before' => 'Stories are India’s quiet export and its deepest cultural currency, and the production house sits at the heart of that economy. We invest in content businesses with a library of value — a back catalogue that earns long after release, relationships with talent and distributors, and the consistency to compound a brand. As streaming and regional content expand the market, we favour houses that',
            'body_accent' => 'own their intellectual property',
            'body_after' => '.',
            'pull_quote' => 'Content as a durable asset, not a one-time gamble.',
            'facts' => ['Owned IP', 'Back-catalogue earnings'],
        ],
        [
            'name' => 'Media & Entertainment',
            'tag' => 'Distribution · Audience · Franchises',
            'image' => 'images/industries/media-entertainment.jpg',
            'image_alt' => 'Media and Entertainment',
            'body_before' => 'Media is where',
            'body_accent' => 'attention becomes a moat',
            'body_after' => '— and in a market as large, young and linguistically diverse as India’s, that attention is only deepening. We invest across the value chain in businesses with audience loyalty, repeatable franchises and multiple ways to monetise the same content — strong regional resonance across North India alongside national reach.',
            'pull_quote' => 'Brands and distribution competitors find very hard to dislodge.',
            'facts' => ['Regional resonance', 'National reach'],
        ],
    ],
];
