<?php

return [
    'page' => [
        'title' => 'Industries',
        'seo_title' => 'Industries · Anmol Pushjai Goel · Nuclear Edge',
        'meta_description' => 'Where Anmol Pushjai Goel invests, and why — durable businesses with moats, capable people and prices that leave room for error, across India with conviction in the North.',
        'og_image' => 'images/industries/redesign-hero-industries.jpg',
    ],

    'sections' => [
        'hero' => [
            'name' => 'Hero',
            'type' => 'hero',
            'sort_order' => 10,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 180],
                'title_first' => ['label' => 'Title line one', 'type' => 'text', 'max' => 140],
                'title_second' => ['label' => 'Title line two', 'type' => 'text', 'max' => 140],
                'description' => ['label' => 'Introduction', 'type' => 'textarea', 'max' => 1800],
                'stats' => [
                    'label' => 'Statistics',
                    'type' => 'repeater',
                    'max_items' => 6,
                    'fields' => [
                        'value' => ['label' => 'Value', 'type' => 'text', 'max' => 40],
                        'label' => ['label' => 'Label', 'type' => 'text', 'max' => 100],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'The Portfolio · Nuclear Edge',
                'title_first' => 'Where we invest,',
                'title_second' => 'and why.',
                'description' => 'We buy durable businesses, run by capable people, at prices that leave room for error, then hold them for the long arc of their growth. We invest across India, with particular conviction in the North we know best.',
                'stats' => [
                    ['_key' => 'hero-stat-1', 'value' => '11', 'label' => 'Industries'],
                    ['_key' => 'hero-stat-2', 'value' => '10-yr', 'label' => 'The test we apply'],
                    ['_key' => 'hero-stat-3', 'value' => 'North', 'label' => 'India conviction'],
                ],
            ],
        ],
        'creed' => [
            'name' => 'Investment Philosophy',
            'type' => 'creed',
            'sort_order' => 20,
            'fields' => [
                'statement_before' => ['label' => 'Statement before accent', 'type' => 'textarea', 'max' => 500],
                'statement_accent' => ['label' => 'Gold accent text', 'type' => 'text', 'max' => 200],
                'statement_after' => ['label' => 'Statement after accent', 'type' => 'textarea', 'max' => 500],
                'lede' => ['label' => 'Supporting lede', 'type' => 'textarea', 'max' => 900],
                'principles' => [
                    'label' => 'Principles',
                    'type' => 'repeater',
                    'max_items' => 8,
                    'fields' => [
                        'title' => ['label' => 'Title', 'type' => 'text', 'max' => 120],
                        'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 400],
                    ],
                ],
            ],
            'content' => [
                'statement_before' => 'Understand the business before the stock. Prize the',
                'statement_accent' => 'moat over the momentum.',
                'statement_after' => 'Then let time do the heavy lifting.',
                'lede' => 'Four questions settle almost everything: what we truly understand, what protects the earnings, who runs the place, and what the price is asking us to believe.',
                'principles' => [
                    ['_key' => 'principle-1', 'title' => 'Circle of competence', 'description' => 'Old-economy cash and the digital frontier, chosen on purpose.'],
                    ['_key' => 'principle-2', 'title' => 'The one question', 'description' => 'Will this business be earning more, ten years from now?'],
                    ['_key' => 'principle-3', 'title' => 'Geography', 'description' => 'All of India, with an on-the-ground edge in the North.'],
                    ['_key' => 'principle-4', 'title' => 'The horizon', 'description' => 'Long-term owners, not traders of tickers.'],
                ],
            ],
        ],
        'portfolio' => [
            'name' => 'Portfolio Introduction',
            'type' => 'portfolio',
            'sort_order' => 30,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1600],
            ],
            'content' => [
                'eyebrow' => 'The Sectors',
                'heading' => 'Where the capital sits.',
                'description' => 'Eleven industries, chosen not by sector label but by one shared test: a business that will still be earning, and earning more, a decade from now. Select any to read the thesis.',
            ],
        ],
        'closing' => [
            'name' => 'Closing Statement',
            'type' => 'closing',
            'sort_order' => 40,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1800],
                'button_label' => ['label' => 'Button label', 'type' => 'text', 'max' => 100],
                'button_url' => ['label' => 'Button destination', 'type' => 'link', 'max' => 2048],
            ],
            'content' => [
                'eyebrow' => 'The Common Thread',
                'heading' => 'Understand. Trust. Respect. Protect.',
                'description' => 'Across every industry, the test is the same: a business we can understand, a moat we can trust, a management we can respect, and a price that protects us if we are wrong. We partner with businesses, and the people who build them, for the years it takes for good companies to become great.',
                'button_label' => 'Start a conversation',
                'button_url' => '#contact',
            ],
        ],
        'contact' => [
            'name' => 'Contact & Footer',
            'type' => 'contact',
            'sort_order' => 50,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 160],
                'email' => ['label' => 'Contact email', 'type' => 'email', 'max' => 254],
                'company_label' => ['label' => 'Company label', 'type' => 'text', 'max' => 100],
                'description' => ['label' => 'Company description', 'type' => 'textarea', 'max' => 1200],
                'linkedin_url' => ['label' => 'LinkedIn URL', 'type' => 'link', 'max' => 2048],
                'twitter_url' => ['label' => 'X / Twitter URL', 'type' => 'link', 'max' => 2048],
                'copyright_name' => ['label' => 'Copyright name', 'type' => 'text', 'max' => 160],
                'footer_role' => ['label' => 'Footer role line', 'type' => 'text', 'max' => 240],
            ],
            'content' => [
                'eyebrow' => 'Investment & collaboration',
                'heading' => 'Let’s talk capital.',
                'email' => 'invest@anmolpushjaigoel.com',
                'company_label' => 'Nuclear Edge',
                'description' => 'A long-horizon portfolio across India, with conviction in the North.',
                'linkedin_url' => 'https://www.linkedin.com/in/anmol-pushjai-goel/',
                'twitter_url' => '#',
                'copyright_name' => 'Anmol Pushjai Goel',
                'footer_role' => 'Entrepreneur · Investor · Tech and AI Policy',
            ],
        ],
    ],

    'items' => [
        [
            'name' => 'Technology',
            'tag' => 'Compute · Platforms · Pricing Power',
            'image' => 'images/industries/technology.jpg',
            'image_alt' => 'Technology',
            'body_before' => 'The compounding engine of the modern economy, and India is no longer merely its back office but a builder of products and platforms in its own right. We back businesses with genuine pricing power: defensible IP, customers who stay, and switching costs that widen the moat each year. We prefer advantage that is structural rather than sentimental, funded by its own cash.',
            'body_accent' => null,
            'body_after' => null,
            'pull_quote' => 'Wary of fashion, fond of fundamentals.',
            'facts' => ['Defensible IP', 'Self-funded growth'],
        ],
        [
            'name' => 'IT Services',
            'tag' => 'Delivery Scale · Client Trust',
            'image' => 'images/industries/it-services.jpg',
            'image_alt' => 'IT Services',
            'body_before' => "One of India's truest moats, built on talent depth, delivery scale, and decades of client trust that rivals cannot replicate overnight. We look for high client retention, revenue spread across sectors, and the discipline to move up the value chain toward outcomes, automation and domain expertise. Durable, cash-rich franchises with long runways for reinvestment.",
            'body_accent' => null,
            'body_after' => null,
            'pull_quote' => '',
            'facts' => ['Noida and Gurugram corridors', 'High client retention'],
        ],
        [
            'name' => 'Data Centres',
            'tag' => 'Digital Infrastructure · Real Assets',
            'image' => 'images/industries/data-centres.jpg',
            'image_alt' => 'Data Centres',
            'body_before' => 'Every application, transaction and model has to live somewhere, and that somewhere is increasingly Indian soil, pushed there by data localisation, cloud adoption and rising digital consumption. Expensive to build, then rewarded with long contracts, recurring revenue and high barriers to entry. We treat it as a multi-decade compounding theme in real infrastructure.',
            'body_accent' => null,
            'body_after' => null,
            'pull_quote' => 'A toll road you build once and collect on for years.',
            'facts' => ['Long-tenor contracts', 'Power and land advantage'],
        ],
        [
            'name' => 'Petroleum',
            'tag' => 'Distribution · Storage · Logistics',
            'image' => 'images/industries/petroleum.jpg',
            'image_alt' => 'Petroleum',
            'body_before' => "Energy is the bloodstream of an industrialising economy, and petroleum stays foundational to India's transport, manufacturing and rural growth. We favour businesses that control distribution, hold strong storage and logistics, and defend margins through the cycle. We want a durable, cash-generative position, not a wager on the price of a single barrel.",
            'body_accent' => null,
            'body_after' => null,
            'pull_quote' => '',
            'facts' => ['North India consumption belt', 'Throughput and infrastructure'],
        ],
        [
            'name' => 'Milk & Dairy',
            'tag' => 'Procurement · Cold Chain · Brand',
            'image' => 'images/industries/milk-dairy.jpg',
            'image_alt' => 'Milk and Dairy',
            'body_before' => 'A great recurring-revenue business hidden in plain sight: a daily, non-discretionary purchase in nearly every Indian household, and North India is the heartland of Indian milk. We invest in strong procurement networks, cold-chain capability and brand loyalty that turns a commodity into a moat. A little earned from millions of customers each day, reinvested for decades.',
            'body_accent' => null,
            'body_after' => null,
            'pull_quote' => 'The closest thing in food to a perpetual annuity.',
            'facts' => ['Punjab · Haryana · UP · Rajasthan', 'Farmer networks'],
        ],
        [
            'name' => 'Transportation & Logistics',
            'tag' => 'Freight Corridors · Route Density',
            'image' => 'images/industries/transportation-logistics.jpg',
            'image_alt' => 'Transportation and Logistics',
            'body_before' => "As goods move, value moves with them, and India's logistics backbone is being rebuilt at historic scale. We back asset-smart operators along the freight corridors, where the Delhi-NCR hub and the region's arterial highways carry some of the densest goods movement in India. We want the discipline to convert volume into consistent free cash flow.",
            'body_accent' => null,
            'body_after' => null,
            'pull_quote' => 'The arteries every other industry quietly relies on.',
            'facts' => ['Delhi-NCR freight hub', 'Repeat customers'],
        ],
        [
            'name' => 'Timber & Wood',
            'tag' => 'Import and Export · Processing',
            'image' => 'images/industries/timber-wood.jpg',
            'image_alt' => 'Timber and Wood',
            'body_before' => "Few associate North India with global trade flows, yet Yamunanagar in Haryana is the plywood and timber capital of the country, and India's construction and furniture demand keeps wood in perpetual short supply. A classic trading and processing business: supplier relationships, working-capital discipline, and port logistics from Kandla to the heartland. An old business done well.",
            'body_accent' => null,
            'body_after' => null,
            'pull_quote' => '',
            'facts' => ['Yamunanagar · Kandla port', 'Working-capital discipline'],
        ],
        [
            'name' => 'Education',
            'tag' => 'Institutions · Brands · Outcomes',
            'image' => 'images/industries/education.jpg',
            'image_alt' => 'Education',
            'body_before' => "The most defensible business in any aspiring economy, driven by relentless demand, deep trust, and pricing power that compounds with reputation. India's young population, and North India's standing as a centre of learning from Delhi to Chandigarh to the coaching capital of Kota, create a tailwind measured in decades. We back the outcomes that turn a campus into a generational franchise.",
            'body_accent' => null,
            'body_after' => null,
            'pull_quote' => 'Reputation compounds. It does not depreciate.',
            'facts' => ['Delhi · Chandigarh · Kota', 'Demonstrated outcomes'],
        ],
        [
            'name' => 'EdTech',
            'tag' => 'Digital Learning · Selective',
            'image' => 'images/industries/edtech.jpg',
            'image_alt' => 'EdTech',
            'body_before' => "EdTech carries quality education from the metros to the smallest towns, where India's appetite for learning meets the reach of its smartphones. We invest selectively, mindful that not every fast-growing platform earns its keep. The test is simple: unit economics that work, and retention that proves the value is real. We want a moat, not a user count.",
            'body_accent' => null,
            'body_after' => null,
            'pull_quote' => 'The opportunity is enormous. Our standard is unforgiving.',
            'facts' => ['Unit-economics first', 'Real retention'],
        ],
        [
            'name' => 'Production Houses',
            'tag' => 'Content · IP · Libraries',
            'image' => 'images/industries/production-houses.jpg',
            'image_alt' => 'Production Houses',
            'body_before' => "Stories are India's quiet export and its deepest cultural currency, and the production house sits at the centre of that economy. We invest in content businesses with a library of value: a back catalogue that keeps earning long after release, relationships with talent and distributors, and the consistency to compound a brand. As streaming widens the market, we favour houses that own their IP.",
            'body_accent' => null,
            'body_after' => null,
            'pull_quote' => 'Content as a durable asset, not a one-time gamble.',
            'facts' => ['Owned IP', 'Back-catalogue earnings'],
        ],
        [
            'name' => 'Media & Entertainment',
            'tag' => 'Distribution · Audience · Franchises',
            'image' => 'images/industries/media-entertainment.jpg',
            'image_alt' => 'Media and Entertainment',
            'body_before' => "Media is where attention becomes a moat, and in a market as large, young and linguistically diverse as India's, that attention only deepens. We invest across the value chain in businesses with audience loyalty, repeatable franchises, and several ways to monetise the same content, pairing regional resonance across North India with national reach.",
            'body_accent' => null,
            'body_after' => null,
            'pull_quote' => 'Brands and distribution that rivals find hard to dislodge.',
            'facts' => ['Regional resonance', 'National reach'],
        ],
    ],
];
