<?php

return [
    'page' => [
        'title' => 'In the News',
        'seo_title' => 'In the News — Anmol Pushjai Goel',
        'meta_description' => 'Anmol Pushjai Goel in News — featured across The Tribune, The Wire, ThePrint, Business Standard, Wisconsin Journal and more.',
        'og_image' => 'images/news/nuclear-edge-office.jpg',
    ],

    'sections' => [
        'hero' => [
            'name' => 'Hero & Coverage Reel',
            'type' => 'hero',
            'sort_order' => 10,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading_before' => ['label' => 'Heading before accent', 'type' => 'text', 'max' => 120],
                'heading_accent' => ['label' => 'Heading accent', 'type' => 'text', 'max' => 80],
                'subline' => ['label' => 'Subline', 'type' => 'text', 'max' => 180],
                'hint' => ['label' => 'Carousel hint', 'type' => 'text', 'max' => 220],
                'background_image' => ['label' => 'Background image', 'type' => 'image'],
                'background_alt' => ['label' => 'Background image alt text', 'type' => 'text', 'max' => 180],
                'coverage' => [
                    'label' => 'Coverage entries',
                    'type' => 'repeater',
                    'max_items' => 60,
                    'fields' => [
                        'outlet' => ['label' => 'Outlet', 'type' => 'text', 'max' => 140],
                        'date' => ['label' => 'Display date', 'type' => 'text', 'max' => 80],
                        'title' => ['label' => 'Headline', 'type' => 'textarea', 'max' => 500],
                        'url' => ['label' => 'Article URL', 'type' => 'link', 'max' => 2048],
                        'image' => ['label' => 'Carousel image', 'type' => 'image'],
                        'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                        'show_in_reel' => [
                            'label' => 'Show in carousel',
                            'type' => 'select',
                            'options' => ['1' => 'Yes', '0' => 'No'],
                        ],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'Press & Media',
                'heading_before' => 'In the',
                'heading_accent' => 'news.',
                'subline' => 'Anmol Pushjai Goel in News',
                'hint' => 'Auto-scrolling · hover to pause · click any clipping to read',
                'background_image' => 'images/news/nuclear-edge-office.jpg',
                'background_alt' => '',
                'coverage' => [
                    [
                        '_key' => 'tribune-sociologist-entrepreneur',
                        'outlet' => 'The Tribune',
                        'date' => 'Jun 25, 2024',
                        'title' => 'The Sociologist Entrepreneur, Anmol Pushjai Goel',
                        'url' => 'https://www.tribuneindia.com/news/business/anmol-pushjai-goel-prominent-indian-entrepreneur-and-tech-policy-expert-redefining-indias-ai-agenda/',
                        'image' => 'images/news/the-tribune-sociologist-entrepreneur.jpg',
                        'image_alt' => 'The Tribune clipping about Anmol Pushjai Goel',
                        'show_in_reel' => '1',
                    ],
                    [
                        '_key' => 'wire-ai-race',
                        'outlet' => 'The Wire',
                        'date' => 'Jun 25, 2024',
                        'title' => 'India Not in the AI Race, Selling Chai Outside the Stadium',
                        'url' => 'https://thewire.in/ptiprnews/anmol-pushjai-goel-prominent-indian-entrepreneur-and-tech-policy-expert-redefining-indias-ai-agenda',
                        'image' => 'images/news/the-wire-ai-race.jpg',
                        'image_alt' => 'The Wire clipping about India and the AI race',
                        'show_in_reel' => '1',
                    ],
                    [
                        '_key' => 'business-standard-nuclear-edge',
                        'outlet' => 'Business Standard',
                        'date' => 'Jun 22, 2024',
                        'title' => 'Nuclear Edge: Company Directors, Revenue & Projects',
                        'url' => 'https://www.business-standard.com/content/press-releases-ani/nuclear-edge-best-it-company-revenue-networth-directors-anmol-pushjai-goel-prominent-indian-entrepreneur-and-ai-policy-expert-126062201052_1.html',
                        'image' => 'images/news/business-standard-nuclear-edge.jpg',
                        'image_alt' => 'Business Standard clipping about Nuclear Edge',
                        'show_in_reel' => '1',
                    ],
                    [
                        '_key' => 'wisconsin-journal-nuclear-edge',
                        'outlet' => 'Wisconsin Journal',
                        'date' => 'Jun 22, 2024',
                        'title' => 'Leading IT Company, Nuclear Edge',
                        'url' => 'https://www.wisconsinjournal.news/news/nuclear-edge-best-it-company-revenue-networth-directors-anmol-pushjai-goel-prominent-indian-entrepreneur-and-ai-policy-expert20260622180340/',
                        'image' => 'images/news/wisconsin-journal-nuclear-edge.jpg',
                        'image_alt' => 'Wisconsin Journal clipping about Nuclear Edge',
                        'show_in_reel' => '1',
                    ],
                    [
                        '_key' => 'theprint-funds-studying',
                        'outlet' => 'ThePrint',
                        'date' => 'Aug 16, 2023',
                        'title' => 'Funds Should Be the Last Thing Stopping Anybody From Studying',
                        'url' => 'https://theprint.in/ani-press-releases/free-ias-coaching-for-underprivileged-aspirants-a-game-changer-by-99notes/1717326/',
                        'image' => 'images/news/theprint-funds-should-be-last.jpg',
                        'image_alt' => 'ThePrint clipping about free IAS coaching',
                        'show_in_reel' => '1',
                    ],
                    [
                        '_key' => 'statesman-99notes',
                        'outlet' => 'The Statesman',
                        'date' => 'Aug 16, 2023',
                        'title' => 'What is 99Notes? Free IAS coaching for underprivileged aspirants',
                        'url' => 'https://www.thestatesman.com/education/what-is-99-notes-ias-coaching-institute-providing-free-coaching-to-underprivileged-aspirants-1503212537.html',
                        'image' => null,
                        'image_alt' => '',
                        'show_in_reel' => '0',
                    ],
                    [
                        '_key' => 'theprint-sunil-oberoi',
                        'outlet' => 'ThePrint',
                        'date' => 'Feb 19, 2024',
                        'title' => 'Top Bureaucrat IAS (R) Sunil Oberoi joins 99Notes',
                        'url' => 'https://theprint.in/ani-press-releases/top-bureaucrat-ias-r-sunil-oberoi-joins-99notes/1971171/',
                        'image' => null,
                        'image_alt' => '',
                        'show_in_reel' => '0',
                    ],
                ],
            ],
        ],
        'index' => [
            'name' => 'Full Coverage Index',
            'type' => 'index',
            'sort_order' => 20,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 140],
                'count_label' => ['label' => 'Count label suffix', 'type' => 'text', 'max' => 80],
                'syndication_label' => ['label' => 'Syndication label', 'type' => 'text', 'max' => 120],
                'syndication_text' => ['label' => 'Syndication text', 'type' => 'textarea', 'max' => 1200],
            ],
            'content' => [
                'eyebrow' => 'The full record',
                'heading' => 'All coverage.',
                'count_label' => 'features',
                'syndication_label' => 'Syndicated across',
                'syndication_text' => 'Google News, Yahoo News, Dailyhunt, ANI, Latestly, PTI, Jaipur Times and 480+ publications worldwide.',
            ],
        ],
        'footer' => [
            'name' => 'Press Footer',
            'type' => 'footer',
            'sort_order' => 30,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 120],
                'email' => ['label' => 'Press email', 'type' => 'email', 'max' => 254],
                'linkedin_label' => ['label' => 'LinkedIn label', 'type' => 'text', 'max' => 80],
                'linkedin_url' => ['label' => 'LinkedIn URL', 'type' => 'link', 'max' => 2048],
                'twitter_label' => ['label' => 'X / Twitter label', 'type' => 'text', 'max' => 80],
                'twitter_url' => ['label' => 'X / Twitter URL', 'type' => 'link', 'max' => 2048],
                'home_label' => ['label' => 'Home link label', 'type' => 'text', 'max' => 80],
                'copyright_name' => ['label' => 'Copyright line', 'type' => 'text', 'max' => 180],
                'role_line' => ['label' => 'Footer role line', 'type' => 'text', 'max' => 240],
            ],
            'content' => [
                'eyebrow' => 'Press & media enquiries',
                'email' => 'press@anmolpushjaigoel.com',
                'linkedin_label' => 'LinkedIn',
                'linkedin_url' => '#',
                'twitter_label' => 'X / Twitter',
                'twitter_url' => '#',
                'home_label' => 'Back to Home',
                'copyright_name' => 'Anmol Pushjai Goel. All rights reserved.',
                'role_line' => 'Entrepreneur · Investor · Tech & AI Policy Voice',
            ],
        ],
    ],
];
