<?php

return [
    'page' => [
        'title' => 'Philanthropy & Governance',
        'seo_title' => 'Philanthropy & Governance · Anmol Pushjai Goel',
        'meta_description' => 'The philanthropy of Anmol Pushjai Goel: a long-term commitment to giving back through education, health and community, carried out alongside partners including Smile Foundation, Aashman Foundation and the Bharat Governance Council.',
        'og_image' => 'images/philanthropy/redesign-hero-portrait.jpg',
    ],

    'sections' => [
        'hero' => [
            'name' => 'Hero',
            'type' => 'hero',
            'sort_order' => 10,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 180],
                'title_first' => ['label' => 'Title line one', 'type' => 'text', 'max' => 120],
                'title_second_before' => ['label' => 'Title words before accent', 'type' => 'text', 'max' => 120],
                'title_second_accent' => ['label' => 'Italic accent text', 'type' => 'text', 'max' => 120],
                'description' => ['label' => 'Introduction', 'type' => 'textarea', 'max' => 1800],
                'stats' => [
                    'label' => 'Principle highlights',
                    'type' => 'repeater',
                    'max_items' => 6,
                    'fields' => [
                        'value' => ['label' => 'Value', 'type' => 'text', 'max' => 80],
                        'label' => ['label' => 'Label', 'type' => 'text', 'max' => 100],
                    ],
                ],
                'portrait' => ['label' => 'Portrait', 'type' => 'image'],
                'portrait_alt' => ['label' => 'Portrait alt text', 'type' => 'text', 'max' => 180],
                'portrait_caption' => ['label' => 'Portrait caption', 'type' => 'text', 'max' => 180],
            ],
            'content' => [
                'eyebrow' => 'Philanthropy & Governance',
                'title_first' => 'Giving that',
                'title_second_before' => '',
                'title_second_accent' => 'lasts.',
                'description' => 'A long-term commitment to giving back, focused on education, health and opportunity for those who need it most. The work is done quietly, close to the ground, and measured over years rather than moments.',
                'stats' => [
                    ['_key' => 'hero-stat-1', 'value' => 'Purpose', 'label' => 'over publicity'],
                    ['_key' => 'hero-stat-2', 'value' => 'People', 'label' => 'over process'],
                    ['_key' => 'hero-stat-3', 'value' => 'Impact', 'label' => 'over optics'],
                ],
                'portrait' => 'images/philanthropy/redesign-hero-portrait.jpg',
                'portrait_alt' => 'Pencil portrait of Anmol Pushjai Goel, a donor recognition from Smile Foundation',
                'portrait_caption' => 'Donor recognition · Smile Foundation',
            ],
        ],
        'creed' => [
            'name' => 'Philosophy',
            'type' => 'creed',
            'sort_order' => 20,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'statement_before' => ['label' => 'Statement before accent', 'type' => 'textarea', 'max' => 600],
                'statement_accent' => ['label' => 'Italic accent text', 'type' => 'text', 'max' => 220],
                'statement_after' => ['label' => 'Statement after accent', 'type' => 'textarea', 'max' => 600],
                'principles' => [
                    'label' => 'Philosophy points',
                    'type' => 'repeater',
                    'max_items' => 8,
                    'fields' => [
                        'title' => ['label' => 'Title', 'type' => 'text', 'max' => 140],
                        'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 400],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'The approach',
                'statement_before' => 'Giving works best when it is',
                'statement_accent' => 'consistent and close to the ground,',
                'statement_after' => 'measured over years rather than announced in a moment.',
                'principles' => [
                    ['_key' => 'creed-1', 'title' => 'Consistent, not occasional', 'description' => 'Steady support that programmes can plan and build around.'],
                    ['_key' => 'creed-2', 'title' => 'Close to the work', 'description' => 'Engaged directly with the people and teams doing it.'],
                    ['_key' => 'creed-3', 'title' => 'Focused', 'description' => 'A few causes supported well, rather than many supported thinly.'],
                    ['_key' => 'creed-4', 'title' => 'For the long term', 'description' => 'Commitment measured in years, not in headlines.'],
                ],
            ],
        ],
        'education' => [
            'name' => 'Why Education',
            'type' => 'feature',
            'sort_order' => 30,
            'fields' => [
                'tag' => ['label' => 'Section tag', 'type' => 'text', 'max' => 180],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 220],
                'heading_accent' => ['label' => 'Italic heading accent', 'type' => 'text', 'max' => 120],
                'body_before' => ['label' => 'Body before accent', 'type' => 'textarea', 'max' => 1800],
                'body_accent' => ['label' => 'Gold accent text', 'type' => 'text', 'max' => 300],
                'body_after' => ['label' => 'Body after accent', 'type' => 'textarea', 'max' => 1800],
                'pull_quote' => ['label' => 'Pull quote', 'type' => 'textarea', 'max' => 600],
                'image' => ['label' => 'Feature image', 'type' => 'image'],
                'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                'image_caption' => ['label' => 'Image caption', 'type' => 'text', 'max' => 180],
                'layout' => [
                    'label' => 'Layout',
                    'type' => 'select',
                    'options' => ['normal' => 'Image left', 'reverse' => 'Image right'],
                ],
            ],
            'content' => [
                'tag' => 'Where it starts',
                'heading' => 'Education opens the',
                'heading_accent' => 'most doors.',
                'body_before' => 'Of all the ways to help, education tends to compound. Its effects reach beyond the individual to families and communities, and they last long after the support itself. Much of the giving is directed toward',
                'body_accent' => 'learning, access and opportunity',
                'body_after' => 'for students who would otherwise go without.',
                'pull_quote' => 'Help that keeps giving, long after it is given.',
                'image' => 'images/philanthropy/redesign-education.jpg',
                'image_alt' => 'Children holding books at a literacy programme',
                'image_caption' => 'Learning support · students in need',
                'layout' => 'normal',
            ],
        ],
        'principles' => [
            'name' => 'Giving Principles',
            'type' => 'principles',
            'sort_order' => 40,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                'items' => [
                    'label' => 'Principles',
                    'type' => 'repeater',
                    'max_items' => 12,
                    'fields' => [
                        'number' => ['label' => 'Number', 'type' => 'text', 'max' => 20],
                        'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                        'heading_accent' => ['label' => 'Italic heading accent', 'type' => 'text', 'max' => 120],
                        'body_before' => ['label' => 'Body before accent', 'type' => 'textarea', 'max' => 1200],
                        'body_accent' => ['label' => 'Emphasis text', 'type' => 'text', 'max' => 300],
                        'body_after' => ['label' => 'Body after accent', 'type' => 'textarea', 'max' => 1200],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'What guides the giving',
                'heading' => 'Principles, not gestures.',
                'items' => [
                    [
                        '_key' => 'principle-1',
                        'number' => '01',
                        'heading' => 'Need before',
                        'heading_accent' => 'recognition',
                        'body_before' => 'Support goes where it is genuinely needed, not where it is most visible. The aim is',
                        'body_accent' => "a real change in someone's circumstances,",
                        'body_after' => 'rather than attention for the giving itself.',
                    ],
                    [
                        '_key' => 'principle-2',
                        'number' => '02',
                        'heading' => 'Substance over',
                        'heading_accent' => 'show',
                        'body_before' => 'Programmes that improve outcomes matter more than events that generate publicity. The measure is',
                        'body_accent' => 'what changes on the ground',
                        'body_after' => 'and whether it holds up over time.',
                    ],
                    [
                        '_key' => 'principle-3',
                        'number' => '03',
                        'heading' => 'Dignity,',
                        'heading_accent' => 'always',
                        'body_before' => 'Everyone supported is treated as a partner in the work, never a beneficiary to be displayed.',
                        'body_accent' => 'Respect for the person',
                        'body_after' => 'comes before any credit for the gift.',
                    ],
                ],
            ],
        ],
        'organizations' => [
            'name' => 'Organizations',
            'type' => 'organizations',
            'sort_order' => 50,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1400],
                'background_image' => ['label' => 'Background image', 'type' => 'image'],
                'background_alt' => ['label' => 'Background image alt text', 'type' => 'text', 'max' => 180],
                'items' => [
                    'label' => 'Organizations',
                    'type' => 'repeater',
                    'max_items' => 20,
                    'fields' => [
                        'role' => ['label' => 'Role', 'type' => 'text', 'max' => 100],
                        'name' => ['label' => 'Organization name', 'type' => 'text', 'max' => 180],
                        'location' => ['label' => 'Location/relationship', 'type' => 'text', 'max' => 140],
                        'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1000],
                        'image' => ['label' => 'Organization image', 'type' => 'image'],
                        'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                        'monogram' => ['label' => 'Monogram fallback', 'type' => 'text', 'max' => 12],
                        'monogram_label' => ['label' => 'Monogram sublabel', 'type' => 'text', 'max' => 100],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'Where the work happens',
                'heading' => 'Partners in the work.',
                'description' => 'The giving is carried out alongside organisations doing serious, sustained work on the ground, from welfare and healthcare to education and governance.',
                'background_image' => 'images/philanthropy/redesign-community-bg.jpg',
                'background_alt' => '',
                'items' => [
                    [
                        '_key' => 'organization-1',
                        'role' => 'Supporter',
                        'name' => 'Smile Foundation',
                        'location' => 'Mumbai',
                        'description' => 'Education, health and livelihood programmes that help underprivileged children and families move toward self-reliance.',
                        'image' => 'images/philanthropy/community-work.jpg',
                        'image_alt' => 'Smile Foundation mobile healthcare unit',
                        'monogram' => '',
                        'monogram_label' => '',
                    ],
                    [
                        '_key' => 'organization-2',
                        'role' => 'Contributor',
                        'name' => 'Aashman Foundation',
                        'location' => 'Panchkula',
                        'description' => 'Grassroots welfare and support for those most in need, at the level where day-to-day help makes the clearest difference.',
                        'image' => 'images/philanthropy/philanthropy-hero-background.jpg',
                        'image_alt' => 'Children supported by grassroots welfare work',
                        'monogram' => '',
                        'monogram_label' => '',
                    ],
                    [
                        '_key' => 'organization-3',
                        'role' => 'Trustee',
                        'name' => 'Bharat Governance Council',
                        'location' => 'Governance · Institutions',
                        'description' => 'Work on the institutions and systems that shape what is possible for people, well before any single act of giving reaches them.',
                        'image' => null,
                        'image_alt' => '',
                        'monogram' => 'BGC',
                        'monogram_label' => 'Governance · Institutions',
                    ],
                ],
            ],
        ],
        'heritage' => [
            'name' => 'Heritage of Service',
            'type' => 'feature',
            'sort_order' => 60,
            'fields' => [
                'tag' => ['label' => 'Section tag', 'type' => 'text', 'max' => 180],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 220],
                'heading_accent' => ['label' => 'Italic heading accent', 'type' => 'text', 'max' => 120],
                'body_before' => ['label' => 'Body before accent', 'type' => 'textarea', 'max' => 1800],
                'body_accent' => ['label' => 'Gold accent text', 'type' => 'text', 'max' => 300],
                'body_after' => ['label' => 'Body after accent', 'type' => 'textarea', 'max' => 1800],
                'pull_quote' => ['label' => 'Pull quote', 'type' => 'textarea', 'max' => 600],
                'image' => ['label' => 'Feature image', 'type' => 'image'],
                'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                'image_caption' => ['label' => 'Image caption', 'type' => 'text', 'max' => 180],
                'layout' => [
                    'label' => 'Layout',
                    'type' => 'select',
                    'options' => ['normal' => 'Image left', 'reverse' => 'Image right'],
                ],
            ],
            'content' => [
                'tag' => 'Why it matters',
                'heading' => 'Service is a',
                'heading_accent' => 'responsibility.',
                'body_before' => 'Giving is treated as an ongoing responsibility rather than an occasional gesture. It is carried on steadily, without fanfare, and judged by',
                'body_accent' => 'what actually changes',
                'body_after' => 'for the people it reaches.',
                'pull_quote' => 'Measured by what changes, not by what is seen.',
                'image' => 'images/philanthropy/shri-mata-mansa-devi-shrine.jpg',
                'image_alt' => 'Shri Mata Mansa Devi Shrine',
                'layout' => 'reverse',
            ],
        ],
        'closing' => [
            'name' => 'Closing Statement',
            'type' => 'closing',
            'sort_order' => 70,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 240],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1800],
                'button_label' => ['label' => 'Button label', 'type' => 'text', 'max' => 100],
                'button_url' => ['label' => 'Button destination', 'type' => 'link', 'max' => 2048],
                'background_image' => ['label' => 'Background image', 'type' => 'image'],
                'background_alt' => ['label' => 'Background image alt text', 'type' => 'text', 'max' => 180],
            ],
            'content' => [
                'eyebrow' => 'The intent',
                'heading' => 'A fair start, for more people.',
                'description' => 'The aim is straightforward and long-term: to widen access to education, health and opportunity, and to help more people reach a life they choose for themselves. The work is steady and unglamorous, and it is meant to last.',
                'button_label' => 'Partner on the work',
                'button_url' => '#contact',
                'background_image' => 'images/philanthropy/redesign-goal-bg.jpg',
                'background_alt' => '',
            ],
        ],
        'contact' => [
            'name' => 'Contact & Footer',
            'type' => 'contact',
            'sort_order' => 80,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                'email' => ['label' => 'Contact email', 'type' => 'email', 'max' => 254],
                'commitment_label' => ['label' => 'Commitment label', 'type' => 'text', 'max' => 120],
                'description' => ['label' => 'Commitment description', 'type' => 'textarea', 'max' => 1200],
                'linkedin_url' => ['label' => 'LinkedIn URL', 'type' => 'link', 'max' => 2048],
                'twitter_url' => ['label' => 'X / Twitter URL', 'type' => 'link', 'max' => 2048],
                'copyright_name' => ['label' => 'Copyright name', 'type' => 'text', 'max' => 160],
                'footer_role' => ['label' => 'Footer role line', 'type' => 'text', 'max' => 240],
            ],
            'content' => [
                'eyebrow' => 'Partnership & philanthropy',
                'heading' => 'Let’s build something lasting.',
                'email' => 'give@anmolpushjaigoel.com',
                'commitment_label' => 'The commitment',
                'description' => 'Education first, community alongside. Support given steadily, and meant to last.',
                'linkedin_url' => 'https://www.linkedin.com/in/anmol-pushjai-goel/',
                'twitter_url' => '#',
                'copyright_name' => 'Anmol Pushjai Goel',
                'footer_role' => 'Entrepreneur · Investor · Tech and AI Policy',
            ],
        ],
    ],
];
