<?php

return [
    'page' => [
        'title' => 'Philanthropy & Governance',
        'seo_title' => 'Philanthropy & Governance — Anmol Pushjai Goel',
        'meta_description' => 'The philanthropy of Anmol Pushjai Goel — built worth over inherited worth, education as the corrective lever, and service carried forward through Smile Foundation, Aashman Foundation, the Bharat Governance Council and the Shri Mata Mansa Devi Shrine Trust.',
        'og_image' => 'images/philanthropy/anmol-pushjai-goel-philanthropy.jpg',
    ],

    'sections' => [
        'hero' => [
            'name' => 'Hero',
            'type' => 'hero',
            'sort_order' => 10,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 180],
                'title_first' => ['label' => 'Title line one', 'type' => 'text', 'max' => 120],
                'title_second_before' => ['label' => 'Title line two before accent', 'type' => 'text', 'max' => 120],
                'title_second_accent' => ['label' => 'Gold accent text', 'type' => 'text', 'max' => 120],
                'description' => ['label' => 'Introduction', 'type' => 'textarea', 'max' => 1800],
                'stats' => [
                    'label' => 'Principle highlights',
                    'type' => 'repeater',
                    'max_items' => 6,
                    'fields' => [
                        'value' => ['label' => 'Value', 'type' => 'text', 'max' => 80],
                        'label' => ['label' => 'Label', 'type' => 'text', 'max' => 100],
                    ],
                ],
                'portrait' => ['label' => 'Portrait', 'type' => 'image'],
                'portrait_alt' => ['label' => 'Portrait alt text', 'type' => 'text', 'max' => 180],
                'portrait_caption' => ['label' => 'Portrait caption', 'type' => 'text', 'max' => 180],
                'background_image' => ['label' => 'Background image', 'type' => 'image'],
                'background_alt' => ['label' => 'Background image alt text', 'type' => 'text', 'max' => 180],
                'scroll_label' => ['label' => 'Scroll label', 'type' => 'text', 'max' => 80],
            ],
            'content' => [
                'eyebrow' => 'Philanthropy & Governance',
                'title_first' => 'Built,',
                'title_second_before' => 'not',
                'title_second_accent' => 'inherited.',
                'description' => 'The most valuable thing a person can own is not what they inherit, but what they build. The giving here is the slow, deliberate work of helping a child build a self that no accident of birth handed them — and therefore one no circumstance can take back.',
                'stats' => [
                    ['_key' => 'hero-stat-1', 'value' => 'Capability', 'label' => 'not charity'],
                    ['_key' => 'hero-stat-2', 'value' => 'Systems', 'label' => 'not slogans'],
                    ['_key' => 'hero-stat-3', 'value' => 'Dignity', 'label' => 'not pity'],
                ],
                'portrait' => 'images/philanthropy/anmol-pushjai-goel-philanthropy.jpg',
                'portrait_alt' => 'Portrait of Anmol Pushjai Goel',
                'portrait_caption' => 'Donor recognition · Smile Foundation',
                'background_image' => 'images/philanthropy/philanthropy-hero-background.jpg',
                'background_alt' => '',
                'scroll_label' => 'The Idea',
            ],
        ],
        'creed' => [
            'name' => 'Philosophy',
            'type' => 'creed',
            'sort_order' => 20,
            'fields' => [
                'statement_before' => ['label' => 'Statement before accent', 'type' => 'textarea', 'max' => 600],
                'statement_accent' => ['label' => 'Gold accent text', 'type' => 'text', 'max' => 220],
                'statement_after' => ['label' => 'Statement after accent', 'type' => 'textarea', 'max' => 600],
                'principles' => [
                    'label' => 'Philosophy points',
                    'type' => 'repeater',
                    'max_items' => 8,
                    'fields' => [
                        'title' => ['label' => 'Title', 'type' => 'text', 'max' => 140],
                        'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 400],
                    ],
                ],
                'background_image' => ['label' => 'Background image', 'type' => 'image'],
                'background_alt' => ['label' => 'Background image alt text', 'type' => 'text', 'max' => 180],
            ],
            'content' => [
                'statement_before' => 'A surname, a town, an income bracket — these are accidents of birth.',
                'statement_accent' => 'A trained mind is earned',
                'statement_after' => '— and once earned, it belongs to you completely.',
                'principles' => [
                    ['_key' => 'creed-1', 'title' => 'Achieved over inherited', 'description' => 'Worth you build holds up even when the room doesn’t recognise you'],
                    ['_key' => 'creed-2', 'title' => 'Corrective, not sentimental', 'description' => 'Returning to a child a future they were always entitled to'],
                    ['_key' => 'creed-3', 'title' => 'Capability handed across', 'description' => 'Not relief offered downward from comfort to need'],
                    ['_key' => 'creed-4', 'title' => 'Slow and structural', 'description' => 'One classroom, one student, one institution at a time'],
                ],
                'background_image' => 'images/philanthropy/philanthropy-hero-background.jpg',
                'background_alt' => '',
            ],
        ],
        'education' => [
            'name' => 'Why Education',
            'type' => 'feature',
            'sort_order' => 30,
            'fields' => [
                'tag' => ['label' => 'Section tag', 'type' => 'text', 'max' => 180],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 220],
                'body_before' => ['label' => 'Body before accent', 'type' => 'textarea', 'max' => 1800],
                'body_accent' => ['label' => 'Gold accent text', 'type' => 'text', 'max' => 300],
                'body_after' => ['label' => 'Body after accent', 'type' => 'textarea', 'max' => 1800],
                'pull_quote' => ['label' => 'Pull quote', 'type' => 'textarea', 'max' => 600],
                'image' => ['label' => 'Feature image', 'type' => 'image'],
                'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                'layout' => [
                    'label' => 'Layout',
                    'type' => 'select',
                    'options' => ['normal' => 'Image left', 'reverse' => 'Image right'],
                ],
            ],
            'content' => [
                'tag' => 'Why education — and almost only education',
                'heading' => 'The one lever that changes the position itself.',
                'body_before' => 'A meal or a one-time gesture helps a person survive today, but leaves their position exactly where it was. Education is the rare intervention that changes the position itself — handing a child the',
                'body_accent' => 'competence, literacy and habit of thinking',
                'body_after' => 'their birth was structured to deny. The focus on underprivileged students is not sentimental. It is corrective.',
                'pull_quote' => 'Not generosity — returning a future quietly denied.',
                'image' => 'images/philanthropy/literacy-programme.jpg',
                'image_alt' => 'Underprivileged students at a literacy programme',
                'layout' => 'normal',
            ],
        ],
        'principles' => [
            'name' => 'Giving Principles',
            'type' => 'principles',
            'sort_order' => 40,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                'items' => [
                    'label' => 'Principles',
                    'type' => 'repeater',
                    'max_items' => 12,
                    'fields' => [
                        'number' => ['label' => 'Number', 'type' => 'text', 'max' => 20],
                        'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                        'body_before' => ['label' => 'Body before accent', 'type' => 'textarea', 'max' => 1200],
                        'body_accent' => ['label' => 'Gold accent text', 'type' => 'text', 'max' => 300],
                        'body_after' => ['label' => 'Body after accent', 'type' => 'textarea', 'max' => 1200],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'What the giving stands for',
                'heading' => 'Principles, not gestures.',
                'items' => [
                    [
                        '_key' => 'principle-1',
                        'number' => '01',
                        'heading' => 'Thinking over certificates',
                        'body_before' => 'A sharp line between schooling that produces certificates and education that produces thinking —',
                        'body_accent' => 'scientific temper in the real sense',
                        'body_after' => ': the ability to ask, to demand evidence, and to arrive at one’s own conclusion rather than the one handed down. An education that lets a young person keep their own voice.',
                    ],
                    [
                        '_key' => 'principle-2',
                        'number' => '02',
                        'heading' => 'Systems over slogans',
                        'body_before' => 'Real change arrives when',
                        'body_accent' => 'positions change',
                        'body_after' => '— when the overlooked gain leverage they didn’t have, when an institution behaves differently rather than announcing that it will. Help a person today; change the system they negotiate against tomorrow.',
                    ],
                    [
                        '_key' => 'principle-3',
                        'number' => '03',
                        'heading' => 'Dignity for the overlooked',
                        'body_before' => 'A consistent sympathy for those a hierarchical society is trained to look past. The giving is an argument against inherited privilege and in favour of',
                        'body_accent' => 'earned dignity',
                        'body_after' => '— a person’s labour, mind and potential have value independent of name or lineage.',
                    ],
                ],
            ],
        ],
        'organizations' => [
            'name' => 'Organizations',
            'type' => 'organizations',
            'sort_order' => 50,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1400],
                'background_image' => ['label' => 'Background image', 'type' => 'image'],
                'background_alt' => ['label' => 'Background image alt text', 'type' => 'text', 'max' => 180],
                'items' => [
                    'label' => 'Organizations',
                    'type' => 'repeater',
                    'max_items' => 20,
                    'fields' => [
                        'role' => ['label' => 'Role', 'type' => 'text', 'max' => 100],
                        'name' => ['label' => 'Organization name', 'type' => 'text', 'max' => 180],
                        'location' => ['label' => 'Location/relationship', 'type' => 'text', 'max' => 140],
                        'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1000],
                        'image' => ['label' => 'Organization image', 'type' => 'image'],
                        'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                        'monogram' => ['label' => 'Monogram fallback', 'type' => 'text', 'max' => 12],
                        'monogram_label' => ['label' => 'Monogram sublabel', 'type' => 'text', 'max' => 100],
                    ],
                ],
            ],
            'content' => [
                'eyebrow' => 'Where the work happens',
                'heading' => 'Worked with, personally.',
                'description' => 'Engagement at close range rather than at arm’s length — staying near enough to the work to see whether a life actually changes, from grassroots welfare to the harder terrain of institutions and governance.',
                'background_image' => 'images/philanthropy/community-work.jpg',
                'background_alt' => '',
                'items' => [
                    [
                        '_key' => 'organization-1',
                        'role' => 'Supporter',
                        'name' => 'Smile Foundation',
                        'location' => 'Mumbai',
                        'description' => 'Education, health and livelihood programmes that move underprivileged children and families toward self-reliance rather than dependence — capability, not charity.',
                        'image' => 'images/philanthropy/community-work.jpg',
                        'image_alt' => 'Smile Foundation mobile healthcare unit',
                        'monogram' => '',
                        'monogram_label' => '',
                    ],
                    [
                        '_key' => 'organization-2',
                        'role' => 'Contributor',
                        'name' => 'Aashman Foundation',
                        'location' => 'Panchkula',
                        'description' => 'Grassroots welfare and upliftment for those most in need — staying engaged at the level where the day-to-day difference in a person’s life is actually made.',
                        'image' => 'images/philanthropy/philanthropy-hero-background.jpg',
                        'image_alt' => 'Children supported by grassroots welfare work',
                        'monogram' => '',
                        'monogram_label' => '',
                    ],
                    [
                        '_key' => 'organization-3',
                        'role' => 'Trustee',
                        'name' => 'Bharat Governance Council',
                        'location' => 'Trusteeship',
                        'description' => 'The structural half of the philosophy in practice — working the levers and systems that decide what is possible for people long before any single act of giving reaches them.',
                        'image' => null,
                        'image_alt' => '',
                        'monogram' => 'BGC',
                        'monogram_label' => 'Governance · Institutions',
                    ],
                ],
            ],
        ],
        'heritage' => [
            'name' => 'Heritage of Service',
            'type' => 'feature',
            'sort_order' => 60,
            'fields' => [
                'tag' => ['label' => 'Section tag', 'type' => 'text', 'max' => 180],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 220],
                'body_before' => ['label' => 'Body before accent', 'type' => 'textarea', 'max' => 1800],
                'body_accent' => ['label' => 'Gold accent text', 'type' => 'text', 'max' => 300],
                'body_after' => ['label' => 'Body after accent', 'type' => 'textarea', 'max' => 1800],
                'pull_quote' => ['label' => 'Pull quote', 'type' => 'textarea', 'max' => 600],
                'image' => ['label' => 'Feature image', 'type' => 'image'],
                'image_alt' => ['label' => 'Image alt text', 'type' => 'text', 'max' => 180],
                'layout' => [
                    'label' => 'Layout',
                    'type' => 'select',
                    'options' => ['normal' => 'Image left', 'reverse' => 'Image right'],
                ],
            ],
            'content' => [
                'tag' => 'A heritage of service',
                'heading' => 'The one inheritance embraced fully.',
                'body_before' => 'The family serves as a trustee with the',
                'body_accent' => 'Shri Mata Mansa Devi Shrine Trust',
                'body_after' => '— framing philanthropy as an inherited responsibility, the stewardship of community institutions carried forward with intention rather than taken up for show. So much of the thinking is about replacing inherited worth with achieved worth; the one inheritance embraced in full is the duty to serve.',
                'pull_quote' => 'Service not as a status to display, but a duty to discharge.',
                'image' => 'images/philanthropy/shri-mata-mansa-devi-shrine.jpg',
                'image_alt' => 'Shri Mata Mansa Devi Shrine',
                'layout' => 'reverse',
            ],
        ],
        'closing' => [
            'name' => 'Closing Statement',
            'type' => 'closing',
            'sort_order' => 70,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 240],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'max' => 1800],
                'button_label' => ['label' => 'Button label', 'type' => 'text', 'max' => 100],
                'button_url' => ['label' => 'Button destination', 'type' => 'link', 'max' => 2048],
                'background_image' => ['label' => 'Background image', 'type' => 'image'],
                'background_alt' => ['label' => 'Background image alt text', 'type' => 'text', 'max' => 180],
            ],
            'content' => [
                'eyebrow' => 'The honest version of the goal',
                'heading' => 'A child’s birth should not set the ceiling of their life.',
                'description' => 'No comfortable version that pretends a single donation solves it. The work is slow and structural. It changes when a child who was meant to be invisible builds something real, walks into the world owning it, and no longer needs anyone’s permission to be there — one classroom, one student, one institution at a time.',
                'button_label' => 'Partner on the work',
                'button_url' => '#contact',
                'background_image' => 'images/philanthropy/literacy-programme.jpg',
                'background_alt' => '',
            ],
        ],
        'contact' => [
            'name' => 'Contact & Footer',
            'type' => 'contact',
            'sort_order' => 80,
            'fields' => [
                'eyebrow' => ['label' => 'Eyebrow', 'type' => 'text', 'max' => 140],
                'heading' => ['label' => 'Heading', 'type' => 'text', 'max' => 180],
                'email' => ['label' => 'Contact email', 'type' => 'email', 'max' => 254],
                'commitment_label' => ['label' => 'Commitment label', 'type' => 'text', 'max' => 120],
                'description' => ['label' => 'Commitment description', 'type' => 'textarea', 'max' => 1200],
                'linkedin_url' => ['label' => 'LinkedIn URL', 'type' => 'link', 'max' => 2048],
                'twitter_url' => ['label' => 'X / Twitter URL', 'type' => 'link', 'max' => 2048],
                'copyright_name' => ['label' => 'Copyright name', 'type' => 'text', 'max' => 160],
                'footer_role' => ['label' => 'Footer role line', 'type' => 'text', 'max' => 240],
            ],
            'content' => [
                'eyebrow' => 'Partnership & philanthropy',
                'heading' => 'Let’s build something lasting.',
                'email' => 'give@anmolpushjaigoel.com',
                'commitment_label' => 'The commitment',
                'description' => 'Education first, systems alongside — the deliberate transfer of the one kind of worth that, once built, belongs to a person for good.',
                'linkedin_url' => '#',
                'twitter_url' => '#',
                'copyright_name' => 'Anmol Pushjai Goel. All rights reserved.',
                'footer_role' => 'Entrepreneur · Investor · Tech & AI Policy Voice',
            ],
        ],
    ],
];
